# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: "Let's Encrypt one cert per VirtualHost checks for {{ user.key }}"
  block:

    - name: "Check that the SSL certs for {{ user.key }} are present"
      ansible.builtin.include_tasks: acmesh_cert_check_vhost.yml
      register: apache_vhost_cert_check_vhosts
      loop: "{{ user.value.users_apache_virtual_hosts | dict2items }}"
      loop_control:
        loop_var: vhost
        label: "{{ vhost.key }}"

    - name: Debug SSL cert check results
      ansible.builtin.debug:
        var: apache_vhost_cert_check_vhosts.results
        verbosity: 2

    - name: Debug users_apache_certs_present
      ansible.builtin.debug:
        var: users_apache_certs_present
        verbosity: 1
      when: users_apache_certs_present is defined

  when: users_cert == "vhost"
  tags:
    - users

- name: "Let's Encrypt one cert per user checks for {{ user.key }}"
  block:

    - name: "Check that the SSL cert for {{ user.key }}.{{ inventory_hostname }} is present"
      ansible.builtin.stat:
        path: "{{ users_cert_dir }}/{{ user.key }}.{{ inventory_hostname }}.cert.pem"
      register: users_apache_tls_cert_check

    - name: "Check that the SSL key for {{ user.key }}.{{ inventory_hostname }} is present"
      ansible.builtin.stat:
        path: "{{ users_cert_dir }}/{{ user.key }}.{{ inventory_hostname }}.key.pem"
      register: users_apache_tls_key_check

    - name: "Check that the SSL ca file for {{ user.key }}.{{ inventory_hostname }} is present"
      ansible.builtin.stat:
        path: "{{ users_cert_dir }}/{{ user.key }}.{{ inventory_hostname }}.ca.pem"
      register: users_apache_tls_ca_check

    - name: Set a fact for the results if any cert is missing
      ansible.builtin.set_fact:
        users_apache_certs_present: false
      when: ( not users_apache_tls_cert_check.stat.exists ) or ( not users_apache_tls_key_check.stat.exists ) or ( not users_apache_tls_ca_check.stat.exists )

    - name: Set a fact for the results if a cert exists and users_apache_certs_present is not defined
      ansible.builtin.set_fact:
        users_apache_certs_present: true
      when:
        - users_apache_certs_present is not defined
        - users_apache_tls_cert_check.stat.exists
        - users_apache_tls_key_check.stat.exists
        - users_apache_tls_ca_check.stat.exists

    - name: Set a fact for the results if a cert exists and users_apache_certs_present is not false
      ansible.builtin.set_fact:
        users_apache_certs_present: true
      when:
        - users_apache_certs_present is defined
        - users_apache_certs_present
        - users_apache_tls_cert_check.stat.exists
        - users_apache_tls_key_check.stat.exists
        - users_apache_tls_ca_check.stat.exists

  when: users_cert == "user"
  tags:
    - users
...
