---
- name: Generate Apache config files
  block:

    - name: One cert per user
      block:

        - name: "Set a fact for users_mdomain to equal {{ user.key }}.{{ inventory_hostname }}"
          set_fact:
            users_mdomain: "{{ user.key }}.{{ inventory_hostname }}"

        - name: "Query the status for {{ user.key }}.{{ inventory_hostname }} using http://localhost/md-status/{{ user.key }}.{{ inventory_hostname }}"
          uri:
            url: "http://localhost/md-status/{{ user.key }}.{{ inventory_hostname }}"
            return_content: true
            status_code:
              - 200
          check_mode: false
          register: users_mdomain_status

        - name: "Debug the mdomain RSA status for {{ users_mdomain_status }}"
          debug:
            var: users_mdomain_status.json.cert.rsa.ocsp.renewal.last.status
            verbosity: 2
          when:
            - users_mdomain_status.json.cert is defined
            - users_mdomain_status.json.name is defined
            - ( users_mdomain_status.json.name | regex_replace('^"') | regex_replace('"$') ) == users_mdomain

        - name: "Debug the mdomain EC status for {{ users_mdomain_status }}"
          debug:
            var: users_mdomain_status.json.cert.secp384r1.ocsp.renewal.last.status
            verbosity: 2
          when:
            - users_mdomain_status.json.cert is defined
            - users_mdomain_status.json.name is defined
            - ( users_mdomain_status.json.name | regex_replace('^"') | regex_replace('"$') ) == users_mdomain

      when: ( apache_mods_enabled is defined ) and ( "md" in apache_mods_enabled )

    - name: "Check if the Apache config for {{ user.key }} exists"
      stat:
        path: "/etc/apache2/sites-available/{{ user.key }}.conf"
      register: users_apache_conf_check

    - name: "As the Apache config for {{ user.key }} exists create a backup of it"
      copy:
        src: "/etc/apache2/sites-available/{{ user.key }}.conf"
        dest: "/etc/apache2/sites-available/.{{ user.key }}.conf.bak"
        remote_src: true
        mode: 0644
        owner: root
        group: root
      when: users_apache_conf_check.stat.exists

    - name: "Apache {{ user.key }} sites-available file present"
      template:
        src: apache.conf.j2
        dest: "/etc/apache2/sites-available/{{ user.key }}.conf"
        trim_blocks: false
        lstrip_blocks: true
        mode: 0644
        owner: root
        group: root
      register: users_apache_conf
      when: user.key != "www-data"

    - name: Apache configtest
      block:

        - name: "Apache {{ user.key }} sites-enabled symlink present"
          command: "a2ensite {{ user.key }}"
          register: users_a2ensite
          changed_when: ( "already enabled" not in users_a2ensite.stdout )

        - name: "apache2ctl configtest to check /etc/apache2/sites-enabled/{{ user.key }}.conf"
          command: apache2ctl configtest
          check_mode: false
          changed_when: false
          register: users_apache2ctl_configtest

        - name: Apache restart
          service:
            name: apache2
            state: restarted
          when: ( users_apache2ctl_configtest is defined ) and ( "Syntax OK" in users_apache2ctl_configtest.stderr )

      rescue:

        - name: Standard out from apache2ctl configtest
          debug:
            msg:
              - "apache2ctl configtest stdout: {{ users_apache2ctl_configtest.stdout }}"
            verbosity: 1

        - name: Standard error from apache2ctl configtest
          debug:
            msg:
              - "apache2ctl configtest stderr: {{ users_apache2ctl_configtest.stderr }}"
            verbosity: 1

        - name: "Apache configtest or restart failed, writing failed config to /etc/apache2/sites-available/.{{ user.key }}.conf.broken"
          copy:
            src: "/etc/apache2/sites-available/{{ user.key }}.conf"
            dest: "/etc/apache2/sites-available/.{{ user.key }}.conf.broken"
            remote_src: true
            mode: 0644
            owner: root
            group: root

        - name: "Check if a backup of the Apache config for {{ user.key }} exists"
          stat:
            path: "/etc/apache2/sites-available/.{{ user.key }}.conf.bak"
          register: users_apache_conf_backup_check

        - name: "Apache configtest or restart failed, reverting to previous config from /etc/apache2/sites-available/.{{ user.key }}.conf.bak"
          copy:
            src: "/etc/apache2/sites-available/.{{ user.key }}.conf.bak"
            dest: "/etc/apache2/sites-available/{{ user.key }}.conf"
            remote_src: true
            mode: 0644
            owner: root
            group: root
          when: users_apache_conf_backup_check.stat.exists

        - name: "Apache {{ user.key }} sites-enabled symlink absent"
          command: "a2dissite {{ user.key }}"
          register: users_a2dissite
          changed_when: '"already enabled" not in users_a2dissite.stdout'
          when: not users_apache_conf_backup_check.stat.exists

        - name: Apache restart
          service:
            name: apache2
            state: restarted

        - name: Fail as apache2ctl configtest or apache2ctl restart failed
          fail:
            msg:
              - "apache2ctl configtest or restart failed for {{ user.key }} and as a result changes that might prevent a restart have been reverted."
              - "The broken config is available in /etc/apache2/sites-available/.{{ user.key }}.conf.broken"
              - "The configtest stderr: {{ users_apache2ctl_configtest.stderr }}"

      when: users_apache_conf.changed

    - name: Pause to allow Apache to sort itself out
      pause:
        seconds: 4

  tags:
    - users
...
