# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Apache user absent
  block:

    - name: "Check the Apache sites-enabled symlink for {{ user.key }}"
      ansible.builtin.stat:
        path: "/etc/apache2/sites-enabled/{{ user.key }}.conf"
      register: users_apache_site_enabled

    - name: "Apache sites-enabled symlink absent for {{ user.key }}"
      ansible.builtin.command:
      args:
        cmd: "a2dissite {{ user.key }}"
        removes: "/etc/apache2/sites-enabled/{{ user.key }}.conf"
      register: users_a2dissite
      when:
        - users_apache_site_enabled.stat.exists | bool
        - users_apache_site_enabled.stat.islnk | bool

    - name: Conditional Apache reload
      block:

        - name: "Run apache2ctl configtest to check deletion of the Apache sites-enabled symlink for {{ user.key }}"
          ansible.builtin.command: apache2ctl configtest
          check_mode: false
          changed_when: false
          failed_when: ( "Syntax OK" not in users_apache2ctl_configtest.stderr )
          register: users_apache2ctl_configtest

        - name: "Apache restarted for {{ user.key }}"
          ansible.builtin.systemd_service:
            name: apache2
            state: restarted
          register: users_apache_restarted
          until:
            - users_apache_restarted.status.SubState is defined
            - users_apache_restarted.status.SubState == "running"
            - users_apache_restarted.status.Result is defined
            - users_apache_restarted.status.Result == "success"
          retries: 2
          delay: 10
          when:
            - users_apachectl_configtest is defined
            - ( "Syntax OK" in users_apachectl_configtest.stderr )

      when:
        - users_a2dissite.changed is defined
        - users_a2dissite.changed | bool

    - name: "Apache sites-available file(s) absent for {{ user.key }}"
      ansible.builtin.file:
        path: "{{ file }}"
        state: absent
      loop:
        - "/etc/apache2/sites-available/{{ user.key }}.conf"
        - "/etc/apache2/sites-available/.{{ user.key }}.conf.broken"
        - "/etc/apache2/sites-available/.{{ user.key }}.conf.bak"
      loop_control:
        loop_var: file
        label: "{{ file }}"

    - name: "Apache suEXEC config absent for {{ user.key }}"
      ansible.builtin.file:
        path: "/etc/apache2/suexec/{{ user.key }}"
        state: absent

    - name: "Certcheck crontab absent for {{ user.key }}"
      ansible.builtin.cron:
        name: "Cert check for {{ user.key }}.{{ ansible_facts.fqdn }}"
        job: "ssl-cert-check -qac {{ users_cert_dir }}/{{ user.key }}.{{ ansible_facts.fqdn }}.cert.pem -e 'root@localhost'"
        state: absent

    - name: "TLS keys and certs for absent for {{ user.key }}"
      ansible.builtin.file:
        path: "{{ path }}"
        state: absent
      loop:
        - "/root/.acme.sh/{{ user.key }}.{{ ansible_facts.fqdn }}_ecc"
        - "/etc/ssl/le/{{ user.key }}.{{ ansible_facts.fqdn }}.cert.pem"
        - "/etc/ssl/le/{{ user.key }}.{{ ansible_facts.fqdn }}.fullchain.pem"
        - "/etc/ssl/le/{{ user.key }}.{{ ansible_facts.fqdn }}.key.pem"
        - "/etc/ssl/le/{{ user.key }}.{{ ansible_facts.fqdn }}.ca.pem"
      loop_control:
        loop_var: path
        label: "{{ path }}"

  tags:
    - users

# TODO There is no Matomo site:delete command yet, when there is this should perhaps be added here
# https://github.com/digitalist-se/extratools/issues/7
# See also matomo_user_absent.yml
...
