---
- name: "Let's Encrypt one cert per VirtualHost checks for {{ vhost.value.users_apache_server_name }}"
  block:

    - name: "Check that the SSL cert for {{ vhost.value.users_apache_server_name }} is present"
      stat:
        path: "{{ le_dir }}/{{ vhost.value.users_apache_server_name }}.cert.pem"
      register: users_apache_tls_cert_check

    - name: "Check that the SSL key for {{ vhost.value.users_apache_server_name }} is present"
      stat:
        path: "{{ le_dir }}/{{ vhost.value.users_apache_server_name }}.key.pem"
      register: users_apache_tls_key_check

    - name: "Check that the SSL ca file for {{ vhost.value.users_apache_server_name }} is present"
      stat:
        path: "{{ le_dir }}/{{ vhost.value.users_apache_server_name }}.ca.pem"
      register: users_apache_tls_ca_check

    - name: Set a fact for the results
      set_fact:
        users_apache_certs_present: true
      when:
        - users_apache_certs_present != False
        - users_apache_tls_cert_check.stat.exists
        - users_apache_tls_key_check.stat.exists
        - users_apache_tls_ca_check.stat.exists

  tags:
    - users
    - apache
    - letsencrypt
...
