---
- name: "Let's Encrypt one cert per VirtualHost checks for {{ vhost.value.users_apache_server_name }}"
  block:

    - name: "Check that the SSL cert for {{ vhost.value.users_apache_server_name }} is present"
      stat:
        path: "{{ le_dir }}/{{ vhost.value.users_apache_server_name }}.cert.pem"
      register: users_apache_tls_cert_check

    - name: "Check that the SSL key for {{ vhost.value.users_apache_server_name }} is present"
      stat:
        path: "{{ le_dir }}/{{ vhost.value.users_apache_server_name }}.key.pem"
      register: users_apache_tls_key_check

    - name: "Check that the SSL ca file for {{ vhost.value.users_apache_server_name }} is present"
      stat:
        path: "{{ le_dir }}/{{ vhost.value.users_apache_server_name }}.ca.pem"
      register: users_apache_tls_ca_check

    - name: Set a fact for the results if any cert is missing
      set_fact:
        users_apache_certs_present: false
      when: ( users_apache_tls_cert_check.stat.exists == False ) or ( users_apache_tls_key_check.stat.exists == False ) or ( users_apache_tls_ca_check.stat.exists == False )

    - name: Set a fact for the results if a cert exists and users_apache_certs_present is not defined
      set_fact:
        users_apache_certs_present: true
      when:
        - users_apache_certs_present is not defined
        - users_apache_tls_cert_check.stat.exists
        - users_apache_tls_key_check.stat.exists
        - users_apache_tls_ca_check.stat.exists

    - name: Set a fact for the results if a cert exists and users_apache_certs_present is not false
      set_fact:
        users_apache_certs_present: true
      when:
        - ( users_apache_certs_present is defined ) and ( users_apache_certs_present != False )
        - users_apache_tls_cert_check.stat.exists
        - users_apache_tls_key_check.stat.exists
        - users_apache_tls_ca_check.stat.exists

    - name: Debug users_apache_certs_present
      debug:
        var: users_apache_certs_present
        verbosity: 1
      when: users_apache_certs_present is defined

  tags:
    - users
...
