---
- name: "Check if the {{ user.key }} site is enabled"
  stat:
    path: "/etc/apache2/sites-enabled/{{ user.key }}.conf"
  register: users_apache_site_enabled
  tags:
    - users-update
    - apache

- name: "Apache {{ user.key }} sites-enabled symlink absent"
  command: "a2dissite {{ user.key }}"
  when: users_apache_site_enabled.stat.exists and users_apache_site_enabled.stat.islnk
  tags:
    - users-update
    - apache

- name: "Apache {{ user.key }} sites-available file(s) absent"
  file:
    path: "{{ file }}"
    state: absent
  loop:
    - "/etc/apache2/sites-available/{{ user.key }}.conf"
    - "/etc/apache2/sites-available/.{{ user.key }}.conf.broken"
    - "/etc/apache2/sites-available/.{{ user.key }}.conf.bak"
  loop_control:
    loop_var: file
    label: "{{ file }}"
  tags:
    - users-update
    - apache

- name: "Certcheck crontab for {{ user.key }} absent"
  cron:
    name: "Cert check for {{ user.key }}.{{ ansible_fqdn }}"
    job: "ssl-cert-check -qac {{ le_dir }}/{{ user.key }}.{{ ansible_fqdn }}.cert.pem -e 'root@localhost'"
    state: absent
  tags:
    - users-update
    - apache
    - letsencrypt

- name: "Keys and certs for {{ user.key }}.{{ ansible_fqdn }} absent"
  file:
    path: "{{ path }}"
    state: absent
  loop:
    - "/root/.acme.sh/{{ user.key }}.{{ ansible_fqdn }}_ecc"
    - "/etc/ssl/le/{{ user.key }}.{{ ansible_fqdn }}.cert.pem"
    - "/etc/ssl/le/{{ user.key }}.{{ ansible_fqdn }}.fullchain.pem"
    - "/etc/ssl/le/{{ user.key }}.{{ ansible_fqdn }}.key.pem"
    - "/etc/ssl/le/{{ user.key }}.{{ ansible_fqdn }}.ca.pem"
  loop_control:
    loop_var: path
  tags:
    - users-update
    - apache
    - letsencrypt

# TODO Restart Apache when site has bee deleted

# There is no Matomo site:delete command yet, when there is this should be added here
# https://github.com/digitalist-se/extratools/issues/7
...
