---
# One cert per VirtualHost
- name: Let's Encrypt cert per vhost role included
  include_role:
    name: acmesh
    tasks_from: letsencrypt
  vars:
    common_name: "{{ vhost.value.users_apache_server_name }}"
    subject_alt_names: "{{ vhost.value.users_apache_server_aliases }}"
    reloadcmd: "service apache2 reload"
  loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
  loop_control:
    loop_var: vhost
  when: ( users_cert is defined ) and ( users_cert == "vhost" ) and ( ansible_check_mode == False )
  tags:
    - apache
    - users-update
    - letsencrypt

- name: Let's Encrypt one cert per user tasks
  block:

    - name: "Set {{ item.key }}.{{ inventory_hostname }} for commonName and ensure subjectAltNames is an empty array"
      set_fact:
        common_name: "{{ item.key }}.{{ inventory_hostname }}"
        subject_alt_names: []
        reloadcmd: "service apache2 reload"
      check_mode: true
      tags:
        - apache
        - users-update
        - letsencrypt

    - name: Set fact for subjectAltNames
      set_fact:
        subject_alt_names: "{% set subject_alt_names = subject_alt_names + [ vhost.value.users_apache_server_name ] + vhost.value.users_apache_server_aliases|default([]) %}{{ subject_alt_names | list }}"
      check_mode: true
      loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
      loop_control:
        loop_var: vhost
      tags:
        - apache
        - users-update
        - letsencrypt

    - debug:
        msg: "subject_alt_names is set to: {{ subject_alt_names }}"
        verbosity: 1
      tags:
        - apache
        - users-update
        - letsencrypt

    - debug:
        msg: "common_name is set to: {{ common_name }}"
        verbosity: 1
      tags:
        - apache
        - users-update
        - letsencrypt

    - name: Let's Encrypt cert role included
      include_role:
        name: acmesh
        tasks_from: letsencrypt
      when: ansible_check_mode == False
      tags:
        - apache
        - users-update
        - letsencrypt

  when: ( users_cert is defined ) and ( users_cert == 'user' )

- name: "Apache {{ item.key }}/{{ users_sites_dir }} directory present"
  file:
    path: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/{{ users_sites_dir }}"
    state: directory
    owner: "{{ item.key }}"
    # group: "{{ apache_user | default('www-data') }}"
    group: "{{ item.value.users_group | default(item.key) }}"
    mode: 0750
  tags:
    - apache
    - users-update

- name: "Apache DocumentRoot(s) present for VitualServers for {{ item.key }}"
  file:
    path: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/{{ users_sites_dir }}/{{ vhost }}"
    state: directory
    owner: "{{ item.key }}"
    # group: "{{ apache_user | default('www-data') }}"
    group: "{{ item.value.users_group | default(item.key) }}"
    mode: 0750
  loop: "{{ item.value.users_apache_virtual_hosts.keys() | list }}"
  loop_control:
    loop_var: vhost
  tags:
    - apache
    - users-update

- name: "HTTP Authentication htpasswd files present for {{ item.key }}"
  include_tasks: htauth.yml
  loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
  loop_control:
    loop_var: vhost
  when: ( vhost.value.users_apache_htauth_users is defined ) and ( vhost.value.users_apache_htauth_users != [] )
  tags:
    - apache
    - users-update
    - users-htauth

- name: "Apache log directory {{ item.value.users_home | default(users_basedir + '/' + item.key) }}/logs present"
  file:
    path: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/logs"
    state: directory
    owner: root
    group: "{{ item.key }}"
    mode: 0750
  tags:
    - apache
    - users-update

- name: "Check that the SSL cert for {{ item.key }}.{{ inventory_hostname }} is present"
  stat:
    path: "{{ le_dir }}/{{ item.key }}.{{ inventory_hostname }}.cert.pem"
  register: users_apache_tls_cert_check
  tags:
    - apache
    - users-update

- name: "Check that the SSL key for {{ item.key }}.{{ inventory_hostname }} is present"
  stat:
    path: "{{ le_dir }}/{{ item.key }}.{{ inventory_hostname }}.key.pem"
  register: users_apache_tls_key_check
  tags:
    - apache
    - users-update

- name: "Check that the SSL ca file for {{ item.key }}.{{ inventory_hostname }} is present"
  stat:
    path: "{{ le_dir }}/{{ item.key }}.{{ inventory_hostname }}.ca.pem"
  register: users_apache_tls_ca_check
  tags:
    - apache
    - users-update

- name: "Check if /etc/apache2/sites-available/{{ item.key }}.conf exists already"
  stat:
    path: "/etc/apache2/sites-available/{{ item.key }}.conf"
  register: users_apache_conf_check
  tags:
    - apache
    - users-update

- name: "Apache {{ item.key }} sites-available file copied"
  copy:
    src: "/etc/apache2/sites-available/{{ item.key }}.conf"
    dest: "/etc/apache2/sites-available/.{{ item.key }}.conf.bak"
    remote_src: true
  when: users_apache_conf_check.stat.exists
  tags:
    - apache
    - users-update

- name: "Apache {{ item.key }} sites-available file present"
  template:
    src: templates/apache.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.key }}.conf"
    trim_blocks: false
    lstrip_blocks: true
  register: users_apache_conf
  tags:
    - apache
    - users-update

- name: "Apache {{ item.key }} sites-enabled symlink present"
  command: "a2ensite {{ item.key }}"
  register: users_a2ensite
  changed_when: '"already enabled" not in users_a2ensite.stdout'
  when: ( users_apache_tls_cert_check.stat.exists ) and ( users_apache_tls_key_check.stat.exists ) and ( users_apache_tls_ca_check.stat.exists )
  tags:
    - apache
    - users-update

- name: Apache configtest
  block:

    - name: "apache2ctl configtest to check /etc/apache2/sites-available/{{ item.key }}.conf"
      command: apache2ctl configtest
      register: users_apache2ctl_configtest
      tags:
        - apache
        - users-update

  rescue:

    - name: "apache2ctl configtest failed, saving failed config"
      copy:
        src: "/etc/apache2/sites-available/{{ item.key }}.conf"
        dest: "/etc/apache2/sites-available/{{ item.key }}.conf.broken"
        remote_src: true
      tags:
        - apache
        - users-update

    - name: "apache2ctl configtest failed so reverting changes"
      copy:
        src: "/etc/apache2/sites-available/.{{ item.key }}.conf.bak"
        dest: "/etc/apache2/sites-available/{{ item.key }}.conf"
        remote_src: true
      when: users_apache_conf_check.stat.exists == True
      tags:
        - apache
        - users-update

    - name: "apache2ctl configtest failed so removing new config and symlink"
      file:
        path: "{{ file }}"
        state: absent
      loop:
        - "/etc/apache2/sites-available/{{ item.key }}.conf"
        - "/etc/apache2/sites-enabled/{{ item.key }}.conf"
      loop_control:
        loop_var: file
      when: users_apache_conf_check.stat.exists == False
      tags:
        - apache
        - users-update

    - name: Fail as apache2ctl configtest failed
      fail:
        msg:
          - "apache2ctl configtest failed for {{ item.key }} and as a result apache has not been restarted and no changes that would prevent a restart have been left in place, you need to check the YAML for this VirtualHost."
          - "The broken config is available in /etc/apache2/sites-available/{{ item.key }}.conf.broken"
          - "The error was: {{ users_apache2ctl_configtest.stderr }}"
      tags:
        - apache
        - users-update

  when: users_apache_conf.changed

- name: "Apache {{ item.key }} sites-enabled symlink absent"
  file:
    path: "/etc/apache2/sites-enabled/{{ item.key }}.conf"
    state: absent
  when: ( users_apache_tls_cert_check.stat.exists == False ) or ( users_apache_tls_key_check.stat.exists == False ) or ( users_apache_tls_ca_check.stat.exists == False )
  tags:
    - apache
    - users-update

- name: "MariaDB password read from {{ item.value.users_home | default(users_basedir + '/' + item.key) }}/.my.cnf"
  shell: "my_print_defaults --defaults-file='{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/.my.cnf' client | grep '^--password' | sed -e 's/--password=//'"
  no_log: true
  register: users_mariadb_password_read
  check_mode: false
  changed_when: false
  tags:
    - users-update

- name: Matomo site tasks
  block:

    - name: "Check if the Matomo {{ matomo_user }} system user account exists"
      shell: "id {{ matomo_user }} && echo true || echo false"
      check_mode: false
      register: user_matomo_user_check
      changed_when: '"no such user" in user_matomo_user_check.stderr'
      tags:
        - matomo
        - users-update

    - name: Matomo site tasks
      block:

        - name: Check if Matomo config file exists
          stat:
            path: "{{ matomo_html }}/config/config.ini.php"
          check_mode: false
          register: user_matomo_config
          tags:
            - matomo
            - users-update

        - name: If Matomo is installed
          block:

            - name: Debug matomo addsite
              debug:
                msg:
                  - "matomo_site_name: {{ vhost.value.users_apache_server_name }}"
                  - "matomo_site_main_url: http://{{ vhost.value.users_apache_server_name }}"
                  - "matomo_site_urls: {% if vhost.value.users_apache_server_aliases is defined %}{{ vhost.value.users_apache_server_aliases | map('regex_replace', '^(.*)$','http://\\1') | list }}{% else %}[]{% endif %}"
                  - "matomo_site_admin: {{ item.key }}"
                verbosity: 1
              when: ( vhost.value.users_cms is not defined ) or ( vhost.value.users_cms is defined and vhost.value.users_cms != "matomo" )
              loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
              loop_control:
                loop_var: vhost
              tags:
                - matomo
                - users-update

            - name: addsite.yml tasks from Matomo role included for each vhost which isn't hosting a Matomo site
              include_role:
                name: matomo
                tasks_from: addsite.yml
              vars:
                matomo_site_name: "{{ vhost.value.users_apache_server_name }}"
                matomo_site_main_url: "http://{{ vhost.value.users_apache_server_name }}"
                # https://gist.github.com/halberom/b1f6eaed16dba1b298e8#gistcomment-2706913
                matomo_site_urls: "{% if vhost.value.users_apache_server_aliases is defined %}{{ vhost.value.users_apache_server_aliases | map('regex_replace', '^(.*)$','http://\\1') | list }}{% else %}[]{% endif %}"
                matomo_site_admin: "{{ item.key }}"
              when: ( vhost.value.users_cms is not defined ) or ( vhost.value.users_cms is defined and vhost.value.users_cms != "matomo" )
              loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
              loop_control:
                loop_var: vhost
              tags:
                - matomo
                - users-update

          when: user_matomo_config.stat.exists

      when: ( user_matomo_user_check is defined ) and ( "no such user" not in user_matomo_user_check.stderr )

  when: ( matomo_user is defined ) and ( matomo_user != "" )

- name: Include WordPress role
  include_role:
    name: wordpress
  vars:
    wordpress_user: "{{ item.key }}"
    wordpress_group: "{{ item.key }}"
    wordpress_docroot: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/{{ users_sites_dir }}/{{ vhost.key }}"
    wordpress_docroot_mode: "0750"
    wordpress_dbname: "{% if vhost.value.wordpress_dbname is defined %}{{ vhost.value.wordpress_dbname }}{% else %}{{ item.value.users_mariadb_databases[0] }}{% endif %}"
    wordpress_dbuser: "{{ item.key }}"
    wordpress_dbpass: "{{ users_mariadb_password_read.stdout | trim | quote }}"
    wordpress_dbprefix: "{{ vhost.value.wordpress_dbprefix | default('wp_') }}"
    wordpress_locale: "{{ vhost.value.wordpress_dbprefix | default('en_GB') }}"
    wordpress_url: "{{ vhost.value.wordpress_url | default('https://' + vhost.value.users_apache_server_name) }}"
    wordpress_title: "{{ vhost.value.wordpress_title | default(vhost.value.users_apache_server_name) }}"
    wordpress_admin_user: "{{ vhost.value.wordpress_admin_user | default(item.key) }}"
    wordpress_admin_email: "{{ vhost.value.wordpress_admin_email | default(item.value.users_email) }}"
    wordpress_notify: "{{ vhost.value.wordpress_notify | default(omit) }}"
    wordpress_notify_from: "{{ users_notify_from }}"
    wordpress_notify_reply_to: "{{ users_notify_reply_to }}"
    wordpress_notify_subject_tag: "{{ users_notify_subject_tag | default('webarchitects') }}"
    wordpress_notify_headers: "{{ users_notify_headers }}"
    wordpress_notify_signature: "{{ users_notify_signature }}"
    wordpress_matomo_user: "{{ matomo_user }}"
    wordpress_matomo_url: "{{ matomo_url }}"
    wordpress_matomo_home: "{{ matomo_home }}"
    wordpress_matomo_html: "{{ matomo_html }}"
    wordpress_matomo_login: "{{ item.key }}"
    wordpress_matomo_login_email: "{{ vhost.value.matomo_login_email | default(item.value.users_email) }}"
    wordpress_matomo_site_name: "{{ vhost.value.users_apache_server_name }}"
  loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
  loop_control:
    loop_var: vhost
  when: ( vhost.value.users_cms is defined ) and ( vhost.value.users_cms == "wordpress" )
  tags:
    - users-update
    - wordpress

- name: Include Matomo role
  include_role:
    name: matomo
  vars:
    matomo_user: "{{ item.key }}"
    matomo_url: "https://{{ vhost.value.users_apache_server_name }}/"
    matomo_home: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
    matomo_html: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/{{ users_sites_dir }}/{{ vhost.key }}"
    matomo_private: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/private"
    matomo_db_username: "{{ item.key }}"
    matomo_db_pass: "{{ users_mariadb_password_read.stdout | trim | quote }}"
    matomo_db_host: localhost
    matomo_dbname: "{% if vhost.value.matomo_dbname is defined %}{{ vhost.value.matomo_dbname }}{% else %}{{ item.value.users_mariadb_databases[0] }}{% endif %}"
    matomo_first_site_name: "{{ vhost.value.matomo_first_site_name | default(inventory_hostname) }}"
    matomo_first_site_url: "{{ vhost.value.matomo_first_site_url | default('http://' + inventory_hostname + '/') }}"
    matomo_first_user: "{{ vhost.value.matomo_first_user | default(item.key) }}"
    matomo_first_user_email: "{{ item.value.users_email | default('root@' + inventory_hostname) }}"
    matomo_notify_from: "{{ users_notify_from }}"
    matomo_notify_reply_to: "{{ users_notify_reply_to }}"
    matomo_notify_subject_tag: "{{ users_notify_subject_tag | default('webarchitects') }}"
    matomo_notify_headers: "{{ users_notify_headers }}"
    matomo_notify_passwd: "{{ vhost.value.matomo_notify_passwd | default(true) }}"
    matomo_email_signature: "{{ users_notify_signature }}"
  loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
  loop_control:
    loop_var: vhost
  when: ( vhost.value.users_cms is defined ) and ( vhost.value.users_cms == "matomo" )
  tags:
    - users-update
    - matomo

- name: Include phpMyAdmin role
  include_role:
    name: phpmyadmin
  vars:
    phpmyadmin_user: "{{ item.key }}"
    phpmyadmin_db: "{% if vhost.value.phpmyadmin_db is defined %}{{ vhost.value.phpmyadmin_db }}{% else %}{{ item.value.users_mariadb_databases[0] }}{% endif %}"
    phpmyadmin_db_user: "{{ item.key }}"
    phpmyadmin_db_pass: "{{ users_mariadb_password_read.stdout | trim | quote }}"
    phpmyadmin_db_socket: /var/run/mysqld/mysqld.sock
    phpmyadmin_db_host: localhost
    phpmyadmin_db_port: 3306
    phpmyadmin_url: "https://{{ vhost.value.users_apache_server_name }}/"
    phpmyadmin_home: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
    phpmyadmin_private: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/private"
    phpmyadmin_html: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/{{ users_sites_dir }}/{{ vhost.key }}"
    phpmyadmin_html_upload_dir: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/{{ users_sites_dir }}/{{ vhost.key }}/uploads"
    phpmyadmin_html_save_dir: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}/{{ users_sites_dir }}/{{ vhost.key }}/saves"
    phpmyadmin_htauth_user: "{{ vhost.value.users_apache_htauth_users[0].name | default(omit) }}"
    phpmyadmin_htauth_pass: "{{ vhost.value.users_apache_htauth_users[0].password | default(omit) }}"
  loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
  loop_control:
    loop_var: vhost
  when: ( vhost.value.users_cms is defined ) and ( vhost.value.users_cms == "phpmyadmin" )
  tags:
    - users-update
    - phpmyadmin

- name: Include daily scripts role
  include_tasks: users_daily_scripts.yml
  loop: "{{ item.value.users_apache_virtual_hosts | dict2items }}"
  loop_control:
    loop_var: vhost
  when: ( vhost.value.users_daily_scripts is defined ) and ( vhost.value.users_daily_scripts != [] )
  tags:
    - users-update
    - users-scripts
...
