---
- name: "Read {{ item.key }} entry from /etc/passwd"
  command: "grep ^{{ item.key }}: /etc/passwd"
  register: users_etc_passwd
  changed_when: false
  tags:
    - users-chroot
    - users-update

- name: "{{ item.key }} present in {{ chroot_dir | default('/chroot') }}/etc/passwd"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/passwd"
    line: "{{ users_etc_passwd.stdout }}"
    state: present
  tags:
    - users-chroot
    - users-update

- name: "Read {{ item.key }} entry from /etc/group"
  command: "grep ^{{ item.key }}: /etc/group"
  register: users_etc_group
  changed_when: false
  tags:
    - users-chroot
    - users-update

- name: "{{ item.key }} present in {{ chroot_dir | default('/chroot') }}/etc/group"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/group"
    line: "{{ users_etc_group.stdout }}"
    state: present
  tags:
    - users-chroot
    - users-update

- name: "Mount point {{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} present"
  file:
    path: "{{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
    owner: root
    group: "{{ item.value.users_home_group | default(item.key) }}"
    mode: "0750"
    state: directory
  tags:
    - users-chroot
    - users-update

- name: "Check if {{ chroot_users_dir | default('/users') }}/{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/users') }}/{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_users_home_mount
  changed_when: '"ABSENT" in users_chroot_users_home_mount.stdout'
  tags:
    - users-update
    - users-chroot

- name: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} present"
  file:
    path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}"
    owner: root
    group: root
    mode: "0750"
    state: directory
  when: '"ABSENT" in users_chroot_users_home_mount.stdout'
  tags:
    - users-update
    - users-chroot

- name: "Chroot directories mounted for {{ item.key }}"
  mount:
    src: "{{ mnt.src }}"
    path: "{{ mnt.path }}"
    opts: "{{ mnt.opts }}"
    fstype: ext4
    state: mounted
  loop:
    - src: "{{ chroot_dir | default('/chroot') }}"
      path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}"
      opts: ro,nosuid,bind,private
    - src: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
      path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
      opts: rw,nodev,nosuid,bind,private
    - src: /run/mysqld
      path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/mysqld"
      opts: ro,nodev,nosuid,noexec,bind,private
    - src: "/run/chroot"
      path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/chroot"
      opts: ro,nodev,nosuid,noexec,bind,private
  loop_control:
    loop_var: mnt
  tags:
    - users-chroot
    - users-update
...
