---
- name: Remove chrooted user
  block:

    - name: "Remove {{ user.key }} from {{ users_chroot_dir }}/etc/passwd"
      lineinfile:
        path: "{{ users_chroot_dir }}/etc/passwd"
        regexp: "^{{ user.key }}:"
        state: absent

    - name: "Remove {{ user.key }} from {{ users_chroot_dir }}/etc/group"
      lineinfile:
        path: "{{ users_chroot_dir }}/etc/group"
        regexp: "^{{ user.key }}:"
        state: absent

    - name: Include tasks to unmount mounted filesystems when Apache is chrooted
      include_tasks: umount.yml
      loop:
        - "{{ users_chroot_users_dir }}/{{ user.key }}{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        - "{{ users_apache_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        - "{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
      loop_control:
        loop_var: users_mount_path
      when: ( users_apache_chroot is defined ) and ( users_apache_chroot )

    - name: Include tasks to unmount mounted filesystems
      include_tasks: umount.yml
      loop:
        - "{{ users_chroot_users_dir }}/{{ user.key }}/run/chroot"
        - "{{ users_chroot_users_dir }}/{{ user.key }}/run/mysqld"
        - "{{ users_chroot_users_dir }}/{{ user.key }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
        - "{{ users_chroot_users_dir }}/{{ user.key }}"
      loop_control:
        loop_var: users_mount_path

    - name: "Directory {{ users_chroot_users_dir }}/{{ user.key }} absent"
      file:
        path: "{{ users_chroot_users_dir }}/{{ user.key }}"
        state: absent

    - name: "Directory {{ users_chroot_dir }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }} absent"
      file:
        path: "{{ users_chroot_dir }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
        state: absent

    - name: "Directory {{ users_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }} absent"
      file:
        path: "{{ users_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        state: absent
      when: ( users_apache_chroot is defined ) and ( users_apache_chroot )

    - name: "Directory {{ users_apache_chroot_users_basedir }}/{{ user.key }} absent"
      file:
        path: "{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        state: absent
      when: ( users_apache_chroot is defined ) and ( users_apache_chroot )

  tags:
    - users
...
