---
- name: Chrooted user present
  block:

    - name: "Read {{ user.key }} entry from /etc/passwd"
      command: "grep ^{{ user.key }}: /etc/passwd"
      check_mode: false
      changed_when: false
      register: users_etc_passwd

    - name: "{{ user.key }} present in {{ users_chroot_dir }}/etc/passwd"
      lineinfile:
        path: "{{ users_chroot_dir }}/etc/passwd"
        line: "{{ users_etc_passwd.stdout }}"
        state: present

    - name: "Read {{ user.key }} entry from /etc/group"
      command: "grep ^{{ user.key }}: /etc/group"
      check_mode: false
      changed_when: false
      register: users_etc_group

    - name: "{{ user.key }} present in {{ users_chroot_dir }}/etc/group"
      lineinfile:
        path: "{{ users_chroot_dir }}/etc/group"
        line: "{{ users_etc_group.stdout }}"
        state: present

    - name: "Chroot directories present for {{ user.key }}"
      file:
        state: directory
        path: "{{ dir.path }}"
        mode: "{{ dir.mode }}"
        owner: "{{ dir.owner }}"
        group: "{{ dir.group }}"
      loop:
        # /chroots/USER
        - path: "{{ users_chroot_users_dir }}/{{ user.key }}"
          mode: "0750"
          owner: root
          group: root
        # /chroot/home/USER
        - path: "{{ users_chroot_dir }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
          mode: "{{ user.value.users_home_mode | default('0750') }}"
          owner: "{{ user.value.users_home_owner | default(user.key) }}"
          group: "{{ user.value.users_home_group | default(user.key) }}"
      loop_control:
        loop_var: dir
        label: "{{ dir.path }}"

    - name: "Chroot directories mounted for {{ user.key }}"
      include_tasks: mount.yml
      vars:
        users_mount_src: "{{ mnt.src }}"
        users_mount_path: "{{ mnt.path }}"
        users_mount_opts: "{{ mnt.opts }}"
        users_mount_fstype: ext4
        users_mount_state: mounted
      loop:
        # mount /chroot at /chroots/USER
        - src: "{{ users_chroot_dir }}"
          path: "{{ users_chroot_users_dir }}/{{ user.key }}"
          opts: ro,nosuid,bind,private
        # mount /home/USER at /chroots/USER/home/USER
        - src: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
          path: "{{ users_chroot_users_dir }}/{{ user.key }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
          opts: rw,nodev,nosuid,bind,private
        # mount /run/mysqld at /chroots/USER/run/mysqld
        - src: /run/mysqld
          path: "{{ users_chroot_users_dir }}/{{ user.key }}/run/mysqld"
          opts: ro,nodev,nosuid,noexec,bind,private
        # mount /run/chroot at /chroots/USER/run/chroot
        - src: "/run/chroot"
          path: "{{ users_chroot_users_dir }}/{{ user.key }}/run/chroot"
          opts: ro,nodev,nosuid,noexec,bind,private
      loop_control:
        loop_var: mnt
        label: "{{ mnt.path }}"

    - name: Additional mounts for user home directory under /var/www both within and outside the chroot when Apache is chrooted
      block:

        # /var/www/users/USER
        - name: "Mount point for users home present in {{ users_apache_chroot_users_basedir }} for Apache chroot"
          file:
            path: "{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
            state: directory
            mode: "{{ user.value.users_home_mode | default('0750') }}"
            owner: "{{ user.value.users_home_owner | default(user.key) }}"
            group: "{{ user.value.users_home_group | default(user.key) }}"

        # /var/www/users/USER
        - name: "Users home mounted ro in {{ users_apache_chroot_users_basedir }} for Apache chroot"
          include_tasks: mount.yml
          vars:
            users_mount_src: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
            users_mount_path: "{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
            users_mount_opts: ro,nodev,nosuid,bind,private
            users_mount_fstype: ext4
            users_mount_state: mounted

        # /chroot/var/www/users/USER
        - name: "Users directory present in the rw chroot under {{ users_apache_chroot_users_basedir }} for Apache chroot"
          file:
            path: "{{ users_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
            state: directory
            mode: "{{ user.value.users_home_mode | default('0750') }}"
            owner: "{{ user.value.users_home_owner | default(user.key) }}"
            group: "{{ user.value.users_home_group | default(user.key) }}"

        # /chroots/www-data/var/www/users/USER
        - name: "Users home mounted rw at {{ users_apache_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }} for Apache chroot"
          include_tasks: mount.yml
          vars:
            users_mount_src: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
            users_mount_path: "{{ users_apache_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
            users_mount_opts: rw,nodev,nosuid,bind,private
            users_mount_fstype: ext4
            users_mount_state: mounted

      when:
        - ( users_apache_chroot is defined ) and ( users_apache_chroot )

  tags:
    - users
...
