# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Remove chrooted user
  block:

    - name: "Remove {{ user.key }} from {{ users_chroot_dir }}/etc/passwd"
      ansible.builtin.lineinfile:
        path: "{{ users_chroot_dir }}/etc/passwd"
        regexp: "^{{ user.key }}:"
        state: absent

    - name: "Remove {{ user.key }} from {{ users_chroot_dir }}/etc/group"
      ansible.builtin.lineinfile:
        path: "{{ users_chroot_dir }}/etc/group"
        regexp: "^{{ user.key }}:"
        state: absent

    - name: Include tasks to unmount mounted filesystems
      ansible.builtin.include_tasks: umount.yml
      loop:
        - "{{ users_chroot_users_dir }}/{{ user.key }}{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        - "{{ users_apache_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        - "{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        - "{{ users_chroot_users_dir }}/{{ user.key }}/run/chroot"
        - "{{ users_chroot_users_dir }}/{{ user.key }}/run/mysqld"
        - "{{ users_chroot_users_dir }}/{{ user.key }}/run/valkey-{{ user.key }}"
        - "{{ users_chroot_users_dir }}/{{ user.key }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
        - "{{ users_chroot_users_dir }}/{{ user.key }}"
      loop_control:
        loop_var: users_mount_path

    - name: "Directory {{ users_chroot_users_dir }}/{{ user.key }} absent"
      ansible.builtin.file:
        path: "{{ users_chroot_users_dir }}/{{ user.key }}"
        state: absent

    - name: "Directory {{ users_chroot_dir }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }} absent"
      ansible.builtin.file:
        path: "{{ users_chroot_dir }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
        state: absent

    - name: "Directory {{ users_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }} absent"
      ansible.builtin.file:
        path: "{{ users_chroot_dir }}{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        state: absent

    - name: "Directory {{ users_apache_chroot_users_basedir }}/{{ user.key }} absent"
      ansible.builtin.file:
        path: "{{ users_apache_chroot_users_basedir }}/{{ user.key }}"
        state: absent

  tags:
    - users
...
