---
- name: "Read {{ item.key }} entry from /etc/passwd"
  command: "grep ^{{ item.key }}: /etc/passwd"
  register: users_etc_passwd
  changed_when: false
  tags:
    - users-update

- name: "{{ item.key }} present in {{ chroot_dir | default('/chroot') }}/etc/passwd"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/passwd"
    line: "{{ users_etc_passwd.stdout }}"
    state: present
  tags:
    - users-update

- name: "Read {{ item.key }} entry from /etc/group"
  command: "grep ^{{ item.key }}: /etc/group"
  register: users_etc_group
  changed_when: false
  tags:
    - users-update

- name: "{{ item.key }} present in {{ chroot_dir | default('/chroot') }}/etc/group"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/group"
    line: "{{ users_etc_group.stdout }}"
    state: present
  tags:
    - users-update

- name: "Mount point {{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default('/home/' + item.key) }} present"
  file:
    path: "{{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default('/home/' + item.key) }}"
    state: directory
    owner: root
    group: "{{ item.value.users_home_group | default(item.key) }}"
    mode: 0750
  tags:
    - users-update

- name: "Mount script for {{ item.key }} written to /etc/fstab.d/{{ item.key }}"
  template:
    src: templates/fstab.j2
    dest: "/etc/fstab.d/{{ item.key }}"
    mode: 0750
  tags:
    - users-update

- name: "Check if {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }} is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }} >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_mount
  changed_when: '"PRESENT" not in users_chroot_mount.stdout'
  tags:
    - users-update

- name: "Mount {{ chroot_dir | default('/chroot') }} at {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}"
  command: "mount --make-private -t ext4 -o ro,bind,nosuid {{ chroot_dir | default('/chroot') }} {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}"
  when: '"ABSENT" in users_chroot_mount.stdout'
  tags:
    - users-update

- name: "Check if {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}{{ item.value.users_home | default('/home/' + item.key) }} is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}{{ item.value.users_home | default('/home/' + item.key) }} >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_home_mount
  changed_when: '"PRESENT" not in users_chroot_home_mount.stdout'
  tags:
    - users-update

- name: "Mount {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}{{ item.value.users_home | default('/home/' + item.key) }}"
  command: "mount --make-private -t ext4 -o rw,bind,nodev,nosuid {{ item.value.users_home | default('/home/' + item.key) }} {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}{{ item.value.users_home | default('/home/' + item.key) }}"
  when: '"ABSENT" in users_chroot_home_mount.stdout'
  tags:
    - users-update

- name: "Check if /run/mysqld at {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/mysqld is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/mysqld >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_mysqld_mount
  changed_when: '"PRESENT" not in users_chroot_mysqld_mount.stdout'
  tags:
    - users-update

- name: "Mount /run/mysqld at {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/mysqld"
  command: "mount --make-private -t ext4 -o ro,bind,nodev,nosuid,noexec /run/mysqld {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/mysqld"
  when: '"ABSENT" in users_chroot_mysqld_mount.stdout'
  tags:
    - users-update

- name: "Check if /run/chroot at {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/chroot is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/chroot >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_run_chroot_mount
  changed_when: '"PRESENT" not in users_chroot_run_chroot_mount.stdout'
  tags:
    - users-update

- name: "Mount /run/chroot at {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/chroot"
  command: "mount --make-private -t ext4 -o ro,bind,nodev,nosuid,noexec /run/chroot {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/chroot"
  when: '"ABSENT" in users_chroot_run_chroot_mount.stdout'
  tags:
    - users-update
...
