---
- name: Remove chrooted user
  block:

    - name: "Remove {{ user.key }} from {{ chroot_dir | default('/chroot') }}/etc/passwd"
      lineinfile:
        path: "{{ chroot_dir | default('/chroot') }}/etc/passwd"
        regexp: "^{{ user.key }}:"
        state: absent

    - name: "Remove {{ user.key }} from {{ chroot_dir | default('/chroot') }}/etc/group"
      lineinfile:
        path: "{{ chroot_dir | default('/chroot') }}/etc/group"
        regexp: "^{{ user.key }}:"
        state: absent

    - name: Include tasks to unmount mounted disks
      include_tasks: umount.yml
      loop:
        - "{{ chroot_users_dir | default('/users') }}/{{ user.key }}/run/chroot"
        - "{{ chroot_users_dir | default('/users') }}/{{ user.key }}/run/mysqld"
        - "{{ chroot_users_dir | default('/users') }}{{ user.key }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
        - "{{ chroot_users_dir | default('/users') }}/{{ user.key }}"
      loop_control:
        loop_var: users_mount_point

    - name: "Directory {{ chroot_users_dir | default('/users') }}/{{ user.key }} absent"
      file:
        path: "{{ chroot_users_dir | default('/users') }}/{{ user.key }}"
        state: absent

    - name: "Directory {{ chroot_dir | default('/chroot') }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }} absent"
      file:
        path: "{{ chroot_dir | default('/chroot') }}{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
        state: absent

  tags:
    - users
...
