---
- name: "Remove {{ item.key }} from {{ chroot_dir | default('/chroot') }}/etc/passwd"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/passwd"
    regexp: "^{{ item.key }}:"
    state: absent
  tags:
    - users-update

- name: "Remove {{ item.key }} from {{ chroot_dir | default('/chroot') }}/etc/group"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/group"
    regexp: "^{{ item.key }}:"
    state: absent
  tags:
    - users-update

# /run/chroot
- name: "Check if {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/chroot is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/chroot >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_run_chroot_mount
  tags:
    - users-update

- name: "Unmount {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/chroot"
  command: "umount -l {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/chroot"
  ignore_errors: true
  register: users_chroot_run_chroot_mountpoint_umount
  changed_when: '"not mounted" not in users_chroot_run_chroot_mountpoint_umount.stderr'
  when: '"PRESENT" in users_chroot_run_chroot_mount.stdout'
  tags:
    - users-update

# /run/mysql
- name: "Check if {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/mysqld is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/mysqld >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_mysqld_mount
  tags:
    - users-update

- name: "Unmount {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/mysqld"
  command: "umount -l {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}/run/mysqld"
  ignore_errors: true
  register: users_chroot_mysqld_mountpoint_umount
  changed_when: '"not mounted" not in users_chroot_mysqld_mountpoint_umount.stderr'
  when: '"PRESENT" in users_chroot_mysqld_mount.stdout'
  tags:
    - users-update

# /chroot-users/$USER/home/$USER
- name: "Check if {{ chroot_users_dir | default('/chroot-users') }}{{ item.key }}{{ item.value.users_home | default('/home/' + item.key) }} is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/chroot-users') }}{{ item.key }}{{ item.value.users_home | default('/home/' + item.key) }} >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_users_home_mount
  tags:
    - users-update

- name: "Unmount {{ chroot_users_dir | default('/chroot-users') }}{{ item.key }}{{ item.value.users_home | default('/home/' + item.key) }}"
  command: "umount -l {{ chroot_users_dir | default('/chroot-users') }}{{ item.key }}{{ item.value.users_home | default('/home/' + item.key) }}"
  ignore_errors: true
  register: users_chroot_home_mountpoint_umount
  changed_when: '"not mounted" not in users_chroot_home_mountpoint_umount.stderr'
  when: '"PRESENT" in users_chroot_users_home_mount.stdout'
  tags:
    - users-update

# /chroot-users/$USER
- name: "Check if {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }} is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}  >/dev/null && echo PRESENT || echo ABSENT"
  register: users_chroot_mount
  tags:
    - users-update

- name: "Unmount {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}"
  command: "umount -l {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}"
  ignore_errors: true
  register: users_chroot_mountpoint_umount
  changed_when: '"not mounted" in users_chroot_mountpoint_umount.stdout'
  when: '"PRESENT" in users_chroot_mount.stdout'
  tags:
    - users-update

- name: "Directory {{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }} absent"
  file:
    path: "{{ chroot_users_dir | default('/chroot-users') }}/{{ item.key }}"
    state: absent
  tags:
    - users-update

- name: "Directory {{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default('/home/' + item.key) }} absent"
  file:
    path: "{{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default('/home/' + item.key) }}"
    state: absent
  tags:
    - users-update

- name: "Mount script at /etc/fstab.d/{{ item.key }} absent"
  file:
    path: "/etc/fstab.d/{{ item.key }}"
    state: absent
  tags:
    - users-update
...
