---
- name: "Read {{ item.key }} entry from /etc/passwd"
  command: "grep ^{{ item.key }}: /etc/passwd"
  register: users_etc_passwd
  changed_when: false
  tags:
    - users-chroot
    - users-update

- name: "{{ item.key }} present in {{ chroot_dir | default('/chroot') }}/etc/passwd"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/passwd"
    line: "{{ users_etc_passwd.stdout }}"
    state: present
  tags:
    - users-chroot
    - users-update

- name: "Read {{ item.key }} entry from /etc/group"
  command: "grep ^{{ item.key }}: /etc/group"
  register: users_etc_group
  changed_when: false
  tags:
    - users-chroot
    - users-update

- name: "{{ item.key }} present in {{ chroot_dir | default('/chroot') }}/etc/group"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/group"
    line: "{{ users_etc_group.stdout }}"
    state: present
  tags:
    - users-chroot
    - users-update

- name: "Mount points for {{ item.key }} present"
  file:
    path: "{{ dir:path }}"
    owner: "{{ dir:owner }}"
    group: "{{ dir:group }}"
    mode: "{{ dir:mode }}"
    state: directory
  loop:
    - path: "{{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
      owner: root
      group: "{{ item.value.users_home_group | default(item.key) }}"
      mode: "0750"
    - path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}"
      owner: root
      group: root
      mode: "0750"
  loop_control:
    loop_var: dir
  tags:
    - users-chroot
    - users-update

# - name: "Mount point {{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} present"
#   file:
#     path: "{{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
#     state: directory
#     owner: root
#     group: "{{ item.value.users_home_group | default(item.key) }}"
#     mode: 0750
#   tags:
#     - users-chroot
#     - users-update
# 
# # This check and the following fail shouldn't be needed
# - name: "Check that {{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} is present"
#   stat:
#     path: "{{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
#   register: users_chroot_home_check
#   tags:
#     - users-chroot
#     - users-upate
# 
# - name: "Fail if {{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} doesn't exist"
#   fail:
#     msg: "The directory {{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} doesn't exist"
#   when: users_chroot_home_check.stat.exists == False
#   tags:
#     - users-chroot
#     - users-upate
# 
# 
# - name: "Mount point {{ chroot_users_dir | default('/users') }}/{{ item.key }} present"
#   file:
#     path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}"
#     state: directory
#     owner: root
#     group: root
#     mode: 0755
#   tags:
#     - users-chroot
#     - users-update

- name: "Chroot directories mounted for {{ item.key }}"
  mount:
    src: "{{ mnt.src }}"
    path: "{{ mnt.path }}"
    opts: "{{ mnt:opts }}"
    fstype: ext4
    state: mounted
  loop:
    - src: "{{ chroot_dir | default('/chroot') }}"
      path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}"
      opts: ro,nosuid,bind,private
    - src: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
      path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
      opts: rw,nodev,nosuid,bind,private
    - src: /run/mysqld
      path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/mysqld"
      opts: ro,nodev,nosuid,noexec,bind,private
    - src: "/run/chroot"
      path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/chroot"
      opts: ro,nodev,nosuid,noexec,bind,private
  loop_control:
    loop_var: mnt
  tags:
    - users-chroot
    - users-update

# - name: "Mount {{ chroot_dir | default('/chroot') }} at {{ chroot_users_dir | default('/users') }}/{{ item.key }} present"
#   mount:
#     src: "{{ chroot_dir | default('/chroot') }}"
#     path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}"
#     fstype: ext4
#     opts: ro,nosuid,bind,private
#     state: mounted
#   tags:
#     - users-chroot
#     - users-update
# 
# - name: "Mount {{ chroot_users_dir | default('/users') }}/{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} present"
#   mount:
#     src: "{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
#     path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
#     fstype: ext4
#     opts: rw,nodev,nosuid,bind,private
#     state: mounted
#   tags:
#     - users-chroot
#     - users-update
# 
# - name: "Mount /run/mysqld at {{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/mysqld present"
#   mount:
#     src: /run/mysqld
#     path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/mysqld"
#     fstype: ext4
#     opts: ro,nodev,nosuid,noexec,bind,private
#     state: mounted
#   tags:
#     - users-chroot
#     - users-update
# 
# - name: "Mount /run/chroot at {{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/chroot present"
#   mount:
#     src: "/run/chroot"
#     path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/chroot"
#     fstype: ext4
#     opts: ro,nodev,nosuid,noexec,bind,private
#     state: mounted
#   tags:
#     - users-chroot
#     - users-update
...
