---
- name: "Remove {{ item.key }} from {{ chroot_dir | default('/chroot') }}/etc/passwd"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/passwd"
    regexp: "^{{ item.key }}:"
    state: absent
  tags:
    - users-update
    - users-chroot

- name: "Remove {{ item.key }} from {{ chroot_dir | default('/chroot') }}/etc/group"
  lineinfile:
    path: "{{ chroot_dir | default('/chroot') }}/etc/group"
    regexp: "^{{ item.key }}:"
    state: absent
  tags:
    - users-update
    - users-chroot

# /run/chroot
- name: "Check if {{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/chroot is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/chroot >/dev/null && echo PRESENT || echo ABSENT"
  check_mode: false
  register: users_chroot_run_chroot_mount
  changed_when: '"PRESENT" in users_chroot_run_chroot_mount.stdout'
  tags:
    - users-update
    - users-chroot

- name: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/chroot unmounted"
  command: "umount -l {{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/chroot"
  args:
    warn: false
  ignore_errors: true
  register: users_chroot_run_chroot_mountpoint_umount
  changed_when: '"not mounted" not in users_chroot_run_chroot_mountpoint_umount.stderr'
  when: '"PRESENT" in users_chroot_run_chroot_mount.stdout'
  tags:
    - users-update
    - users-chroot

# /run/mysql
- name: "Check if {{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/mysqld is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/mysqld >/dev/null && echo PRESENT || echo ABSENT"
  check_mode: false
  register: users_chroot_mysqld_mount
  changed_when: '"PRESENT" in users_chroot_mysqld_mount.stdout'
  tags:
    - users-update
    - users-chroot

- name: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/mysqld unmounted"
  command: "umount -l {{ chroot_users_dir | default('/users') }}/{{ item.key }}/run/mysqld"
  args:
    warn: false
  ignore_errors: true
  register: users_chroot_mysqld_mountpoint_umount
  changed_when: '"not mounted" not in users_chroot_mysqld_mountpoint_umount.stderr'
  when: '"PRESENT" in users_chroot_mysqld_mount.stdout'
  tags:
    - users-update
    - users-chroot

# /users/$USER/home/$USER
- name: "Check if {{ chroot_users_dir | default('/users') }}{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/users') }}{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} >/dev/null && echo PRESENT || echo ABSENT"
  check_mode: false
  register: users_chroot_users_home_mount
  changed_when: '"PRESENT" in users_chroot_users_home_mount.stdout'
  tags:
    - users-update
    - users-chroot

- name: "{{ chroot_users_dir | default('/users') }}{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} unmounted"
  command: "umount -l {{ chroot_users_dir | default('/users') }}{{ item.key }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
  args:
    warn: false
  ignore_errors: true
  register: users_chroot_home_mountpoint_umount
  changed_when: '"not mounted" not in users_chroot_home_mountpoint_umount.stderr'
  when: '"PRESENT" in users_chroot_users_home_mount.stdout'
  tags:
    - users-update
    - users-chroot

# /users/$USER
- name: "Check if {{ chroot_users_dir | default('/users') }}/{{ item.key }} is mounted"
  shell: "findmnt {{ chroot_users_dir | default('/users') }}/{{ item.key }}  >/dev/null && echo PRESENT || echo ABSENT"
  check_mode: false
  register: users_chroot_mount
  changed_when: '"PRESENT" in users_chroot_mount.stdout'
  tags:
    - users-update
    - users-chroot

- name: "{{ chroot_users_dir | default('/users') }}/{{ item.key }} unmounted"
  command: "umount -l {{ chroot_users_dir | default('/users') }}/{{ item.key }}"
  args:
    warn: false
  ignore_errors: true
  register: users_chroot_mountpoint_umount
  changed_when: '"not mounted" in users_chroot_mountpoint_umount.stdout'
  when: '"PRESENT" in users_chroot_mount.stdout'
  tags:
    - users-update
    - users-chroot

- name: "Directory {{ chroot_users_dir | default('/users') }}/{{ item.key }} absent"
  file:
    path: "{{ chroot_users_dir | default('/users') }}/{{ item.key }}"
    state: absent
  tags:
    - users-update
    - users-chroot

- name: "Directory {{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }} absent"
  file:
    path: "{{ chroot_dir | default('/chroot') }}{{ item.value.users_home | default(users_basedir + '/' + item.key) }}"
    state: absent
  tags:
    - users-update
    - users-chroot
...
