---
- name: "Check that required phpMyAdmin variables are defined for {{ vhost.key }} VirtualHost for {{ user.key }}"
  ansible.builtin.assert:
    that:
      - vhost.value.users_apache_type == "php"
      - ( vhost.value.users_apache_robots is defined ) and ( vhost.value.users_apache_robots == "deny" )
      - ( vhost.value.phpmyadmin_dbname is defined ) and ( vhost.value.phpmyadmin_dbname in user.value.users_mariadb_databases )
      - ( vhost.value.phpmyadmin_version is defined )
      - ( vhost.value.phpmyadmin_version == "latest" ) or ( vhost.value.phpmyadmin_version is regex("^[0-9][.][0-9][.][0-9]{1,2}[.]{0,1}[0-9]{0,2}$") )
    quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
  tags:
    - users

- name: "Check that {{ user.key }} is in the phpfpm group if it is present"
  ansible.builtin.assert:
    that:
      - ( "phpfpm" in user.value.users_groups )
    quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
  when: ( "phpfpm" in getent_group )
  tags:
    - users
...
