---
- name: "Check that required phpMyAdmin variables are defined for {{ vhost.key }} VirtualHost for {{ user.key }}"
  assert:
    that:
      - ( "phpfpm" in user.value.users_groups )
      - vhost.value.users_apache_type == "php"
      - ( vhost.value.users_apache_robots is defined ) and ( vhost.value.users_apache_robots == "deny" )
      - ( vhost.value.phpmyadmin_db is defined ) and ( vhost.value.phpmyadmin_db in user.value.users_mariadb_databases )
      - vhost.value.users_apache_sts is defined
      - phpmyadmin_version is defined
...
