# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: "Check the Moodle variables for {{ vhost.key }}"
  block:

    - name: "Check that required Moodle variables are defined for {{ vhost.key }} VirtualHost for {{ user.key }}"
      ansible.builtin.assert:
        that:
          - vhost.value.users_apache_type is regex('^php')
          - vhost.value.moodle_dbname is defined
          - vhost.value.moodle_dbname in user.value.users_mariadb_databases
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Ensure that a Moodle version number is supplied
      ansible.builtin.assert:
        that:
          - vhost.value.moodle_version is defined
          - vhost.value.moodle_version is regex("^[0-9.]*$")
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: "Check that {{ user.key }} is in the phpfpm group if it is present"
      ansible.builtin.assert:
        that:
          - ( "phpfpm" in user.value.users_groups )
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: ( "phpfpm" in ansible_facts.getent_group )

    - name: "Check that the moodle_dbuser is {{ user.key }} is defined for {{ vhost.key }} VirtualHost"
      ansible.builtin.assert:
        that:
          - vhost.value.moodle_dbuser == user.key
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: vhost.value.moodle_dbuser is defined

    - name: "Check that the moodle_dbprefix is less than 8 numbers or letters or underscores for {{ vhost.key }} VirtualHost for {{ user.key }}"
      ansible.builtin.assert:
        that:
          - vhost.value.moodle_dbprefix | length
          - vhost.value.moodle_dbprefix is regex("^[a-zA-Z0-9_]*$")
          - vhost.value.moodle_dbprefix is regex("^.{1,8}$")
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: vhost.value.moodle_dbprefix is defined

    # TODO more checks could be added

  tags:
    - users
...
