---
- name: "Check Matomo variables for {{ user.key }}"
  block:

    - name: "Check that required Matomo variables are defined for {{ vhost.key }} VirtualHost for {{ user.key }}"
      ansible.builtin.assert:
        that:
          - vhost.value.users_apache_type == "php"
          - ( vhost.value.matomo_dbname is defined ) and ( vhost.value.matomo_dbname in user.value.users_mariadb_databases )
          - vhost.value.matomo_first_user is defined
          - vhost.value.matomo_first_user_email is defined
          - vhost.value.users_apache_sts is defined
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: "Check that {{ user.key }} is in the phpfpm group if it is present"
      ansible.builtin.assert:
        that:
          - ( "phpfpm" in user.value.users_groups )
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: ( "phpfpm" in getent_group )

    - name: "Check the matomo_first_site_name for {{ vhost.key }} VirtualHost for {{ user.key }}"
      ansible.builtin.assert:
        that:
          - vhost.value.matomo_first_site_name | length
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: vhost.value.matomo_first_site_name is defined

    - name: "Check the matomo_first_site_url for {{ vhost.key }} VirtualHost for {{ user.key }}"
      ansible.builtin.assert:
        that:
          - vhost.value.matomo_first_site_url is regex("^http:\/\/.*$")
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: vhost.value.matomo_first_site_url is defined

    - name: "Check that the matomo_first_user contains only ascii letters and numbers and is between 2 and 17 characters long for {{ vhost.key }} VirtualHost for {{ user.key }}"
      ansible.builtin.assert:
        that:
          - vhost.value.matomo_first_user | length
          - vhost.value.matomo_first_user is regex("^[a-zA-Z0-9]*$")
          - vhost.value.matomo_first_user is regex("^.{2,17}$")
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: vhost.value.matomo_first_user is defined

    - name: "Check that the matomo_first_user_email is a email address for {{ vhost.key }} VirtualHost for {{ user.key }}"
      ansible.builtin.assert:
        that:
          - vhost.value.matomo_first_user_email is regex("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: vhost.value.matomo_first_user_email is defined

    - name: "Check that matomo_notify_passwd is true or false if it is defined for {{ vhost.key }} VirtualHost for {{ user.key }}"
      ansible.builtin.assert:
        that:
          - ( vhost.value.matomo_notify_passwd ) or ( not vhost.value.matomo_notify_passwd )
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
      when: vhost.value.matomo_notify_passwd is defined

  tags:
    - users
...
