# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: "Chown {{ vhost.key }} for {{ user.key }}"  # noqa: no-free-form
  ansible.builtin.command: "chown -R {{ vhost.value.users_cms_owner }}:{{ vhost.value.users_cms_group }}"
  tags:
    - users

- name: "Chmod {{ vhost.key }} files for {{ user.key }}"
  ansible.builtin.command: "find {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/{{ users_sites_dir }}/{{ vhost.key }} -type f -exec chmod -c {{ vhost.value.users_cms_file_mode }} {} \\;"
  when: vhost.value.users_cms_file_mode is defined
  tags:
    - users

- name: "Chmod {{ vhost.key }} directories for {{ user.key }}"
  ansible.builtin.command: "find {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/{{ users_sites_dir }}/{{ vhost.key }} -type d -exec chmod -c {{ vhost.value.users_cms_directory_mode }} {} \\;"
  when: vhost.value.users_cms_directory_mode is defined
  tags:
    - users
...
