---
- name: "{{ item.value.users_home | default('/home/' + item.key) }}/bin/README.md absent"
  file:
    path: "{{ item.value.users_home | default('/home/' + item.key) }}/bin/README.md"
    state: absent
  tags:
    - users-update
    - users-cron

- name: "Daily cron jobs for {{ item.key }} absent"
  cron:
    name: "Daily cron jobs"
    user: root
    cron_file: "chroot_cron_daily_{{ item.key }}"
    state: absent
  tags:
    - users-update
    - users-cron

- name: "Hourly cron jobs for {{ item.key }} absent"
  cron:
    name: "Hourly cron jobs"
    user: root
    cron_file: "chroot_cron_hourly_{{ item.key }}"
    state: absent
    hour: "*"
  tags:
    - users-update
    - users-cron

- name: "Daily cron jobs for {{ item.key }} absent"
  cron:
    name: "Daily cron jobs"
    user: "{{ item.key }}"
    state: absent
  tags:
    - users-update
    - users-cron

- name: "Hourly cron jobs for {{ item.key }} absent"
  cron:
    name: "Hourly cron jobs"
    user: "{{ item.key }}"
    state: absent
  tags:
    - users-update
    - users-cron

- name: "Daily MariaDB dump cron job absent"
  cron:
    name: "Nightly MySQL database backup for {{ item.key }}"
    user: "{{ item.key }}"
    state: absent
  tags:
    - users-update
    - users-cron
...
