---
- name: "Cron jobs absent for {{ user.key }}"
  block:

    - name: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/README.md absent"
      file:
        path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/README.md"
        state: absent

    - name: "Daily cron jobs for {{ user.key }} absent"
      cron:
        name: "Daily cron jobs"
        user: root
        cron_file: "chroot_cron_daily_{{ user.key }}"
        state: absent

    - name: "Hourly cron jobs for {{ user.key }} absent"
      cron:
        name: "Hourly cron jobs"
        user: root
        cron_file: "chroot_cron_hourly_{{ user.key }}"
        state: absent
        hour: "*"

    - name: "Cron job files for {{ user.key }} absent"
      file:
        path: "/etc/cron.d/{{ file }}"
        state: absent
      loop:
        - "chroot_cron_daily_{{ user.key }}"
        - "chroot_cron_hourly_{{ user.key }}"
      loop_control:
        loop_var: file

    - name: "Daily cron jobs for {{ user.key }} absent"
      cron:
        name: "Daily cron jobs"
        user: "{{ user.key }}"
        state: absent

    - name: "Hourly cron jobs for {{ user.key }} absent"
      cron:
        name: "Hourly cron jobs"
        user: "{{ user.key }}"
        state: absent

    - name: "Daily deletion of users TMPDIR files which are older than a week absent"
      cron:
        name: "Daily deletion of TMPDIR files for {{ user.key }}"
        user: "{{ user.key }}"
        state: absent

    - name: "Daily MariaDB dump cron job absent"
      cron:
        name: "Nightly MySQL database backup for {{ user.key }}"
        user: "{{ user.key }}"
        state: absent

    - name: "Cron jobs defined at a user level absent"
      cron:
        name: "{{ job.name }}"
        state: absent
      loop: "{{ users.value.users_cron_jobs }}"
      loop_control:
        loop_var: job
        label: "{{ job.name }}"
      when: ( users.value.users_cron_jobs is defined ) and ( users.value.users_cron_jobs != [] )

  tags:
    - users
...
