---
- name: Firewall packages present
  apt:
    pkg:
      - iptables
      - iptables-persistent
      - nftables
      - netfilter-persistent
      - python3-pyinotify
    state: present

- name: IPv4 iptables rules in place
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    mode: 0644
    owner: root
    group: root
    backup: true

- name: IPv4 iptables rules restored
  shell: "iptables-restore < /etc/iptables/rules.v4"

- name: fail2ban restarted
  service:
    name: fail2ban
    state: restarted
...
