# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---

# WIP This needs lots more work!

- name: User group members configured
  block:

    - name: Slurp /etc/passwd
      ansible.builtin.slurp:
        src: /etc/passwd
      register: users_etc_passwd_b64encoded

    - name: Set a fact for /etc/passwd
      ansible.builtin.set_fact:
        users_etc_passwd: "{{ users_etc_passwd_b64encoded['content'] | ansible.builtin.b64decode | community.general.jc('passwd') }}"

    - name: Debug users_etc_passwd
      ansible.builtin.debug:
        var: users_etc_passwd
        verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}"
      tags:
        - debug

    - name: Slurp /etc/group
      ansible.builtin.slurp:
        src: /etc/group
      register: users_etc_group_b64encoded

    - name: Set a fact for /etc/group
      ansible.builtin.set_fact:
        users_etc_group: "{{ users_etc_group_b64encoded['content'] | ansible.builtin.b64decode | community.general.jc('group') }}"

    - name: Debug users_etc_group
      ansible.builtin.debug:
        var: users_etc_group
        verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}"
      tags:
        - debug

    - name: "Debug users_etc_group item for {{ user.value.users_group | default(user.key) }}"
      ansible.builtin.debug:
        msg: "{{ users_etc_group | community.general.json_query(users_etc_group_jpq) }}"
        verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}"
      vars:
        users_etc_group_jpq: "[?group_name=='{{ user.value.users_group | ansible.builtin.default(user.key) }}']|[0]"
      tags:
        - debug

    - name: "Set a sorted list for the users that are members of the group {{ user.value.users_group | default(user.key) }}"
      ansible.builtin.set_fact:
        users_members: "{{ (users_etc_group | community.general.json_query(users_etc_group_jpq)).members | ansible.builtin.sort }}"
      vars:
        users_etc_group_jpq: "[?group_name=='{{ user.value.users_group | ansible.builtin.default(user.key) }}']|[0]"

    - name: Debug users_members
      ansible.builtin.debug:
        var: users_members
        verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}0{% else %}1{% endif %}"
      tags:
        - debug

    - name: Group members configured
      block:

        - name: "Debug users that are members of the group {{ user.value.users_group | default(user.key) }}"
          ansible.builtin.debug:
            msg: "User {{ user.value.users_group | default(user.key) }} to have {{ user.value.users_group_members | ansible.builtin.join(', ') }} as member(s) of their group"

        - name: "Check the existance of the users that are members of the group {{ user.value.users_group | default(user.key) }}"
          ansible.builtin.assert:
            that:
              - users_mbr in (users_etc_passwd | community.general.json_query('[].username'))
            quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"
            fail_msg: "The {{ users_mbr }} user need to exist before it can be added to the group {{ user.value.users_group | default(user.key) }}"
          loop: "{{ user.value.users_group_members }}"
          loop_control:
            loop_var: users_mbr
            label: "{{ users_mbr }}"

        - name: "Group memberships configured for the group {{ user.value.users_group | default(user.key) }}"
          ansible.builtin.command:
            cmd: "usermod -G {{ user.value.users_group_members | ansible.builtin.join(',') }} {{ user.value.users_group | default(user.key) }}"
          changed_when: true

      when: users_members != (user.value.users_group_members | ansible.builtin.sort)

  tags:
    - users
...
