# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Groups and group members configured for users not absent
  block:

    - name: Slurp /etc/passwd
      ansible.builtin.slurp:
        src: /etc/passwd
      register: users_etc_passwd_b64encoded

    - name: Set a fact for /etc/passwd
      ansible.builtin.set_fact:
        users_etc_passwd: "{{ users_etc_passwd_b64encoded['content'] | ansible.builtin.b64decode | community.general.jc('passwd') }}"

    - name: Debug users_etc_passwd
      ansible.builtin.debug:
        var: users_etc_passwd
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      tags:
        - debug

    - name: Set a fact for users existing
      ansible.builtin.set_fact:
        users_existing: "{{ users_etc_passwd | community.general.json_query('[].username') | ansible.builtin.sort }}"

    - name: Debug users_existing
      ansible.builtin.debug:
        var: users_existing
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      tags:
        - debug

    - name: Slurp /etc/group
      ansible.builtin.slurp:
        src: /etc/group
      register: users_etc_group_b64encoded

    - name: Set a fact for /etc/group
      ansible.builtin.set_fact:
        users_etc_group: "{{ users_etc_group_b64encoded['content'] | ansible.builtin.b64decode | community.general.jc('group') }}"

    - name: Debug users_etc_group
      ansible.builtin.debug:
        var: users_etc_group
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      tags:
        - debug

    - name: Set a fact for users_groups_existing
      ansible.builtin.set_fact:
        users_groups_existing: "{{ users_etc_group | community.general.json_query('[].group_name') | ansible.builtin.sort }}"

    - name: Debug users_groups_existing
      ansible.builtin.debug:
        var: users_groups_existing
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      tags:
        - debug

    - name: Debug users_update_groups
      ansible.builtin.debug:
        var: users_update_groups
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      tags:
        - debug

    - name: Add users that have no state or have a state not set to absent and have groups defined to the list of users to update
      ansible.builtin.set_fact:
        users_update_groups: "{{ users_update_groups + [user.key] }}"
      loop: "{{ users | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: user
        label: "{{ user.key }}"
      when:
        - (user.key != "root")
        - >-
          ((user.value.users_state is not defined) or
          ((user.value.users_state is defined) and (user.value.users_state != "absent")))
        - (user.value.users_groups is defined) and (user.value.users_groups != [])

    - name: Debug users_update_groups
      ansible.builtin.debug:
        var: users_update_groups
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      tags:
        - debug

    - name: >-
        Add users that that have no state or have a state not set to absent and are listed in users groups members to the list of users to update
      ansible.builtin.set_fact:
        users_update_groups: "{{ users_update_groups + user.value.users_group_members }}"
      loop: "{{ users | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: user
        label: "{{ user.key }}"
      when:
        - (user.key != "root")
        - >-
          ((user.value.users_state is not defined) or
          ((user.value.users_state is defined) and (user.value.users_state != "absent")))
        - (user.value.users_group_members is defined) and (user.value.users_group_members != [])

    - name: Debug users_update_groups
      ansible.builtin.debug:
        var: users_update_groups
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      tags:
        - debug

    - name: Ensure that users_update_groups is sorted and unique
      ansible.builtin.set_fact:
        users_update_groups: "{{ users_update_groups | ansible.builtin.sort | ansible.builtin.unique }}"

    - name: Debug users_update_groups
      ansible.builtin.debug:
        var: users_update_groups
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      tags:
        - debug

    - name: Include tasks to update group for all users
      ansible.builtin.include_tasks: group.yml
      loop: "{{ users_update_groups }}"
      loop_control:
        loop_var: user_update
        label: "{{ user_update }}"
      when:
        - users_update_groups is defined
        - users_update_groups != []
        - user_update in users_existing

  tags:
    - users
...
