# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: User group members configured
  block:

    - name: "Debug the users that are members of the users group for {{ user_member }}"
      ansible.builtin.debug:
        msg: "{{ user_member }} is a member of {{ user.key }}'s group"
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      loop: "{{ users | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: user
        label: "{{ user.key }}"
      when:
        - user.value.users_group_members is defined
        - user.value.users_group_members != []
        - user_member in user.value.users_group_members
        - >-
          ((user.value.users_state is defined) and (user.value.users_state == "present")) or
          user.value.users_state is not defined

    - name: "Generate a list of users that are members of the users group for {{ user_member }}"
      ansible.builtin.set_fact:
        users_grp_mbrs: "{{ users_grp_mbrs + [user.key] }}"
      loop: "{{ users | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: user
        label: "{{ user.key }}"
      when:
        - user.value.users_group_members is defined
        - user.value.users_group_members != []
        - user_member in user.value.users_group_members
        - >-
          ((user.value.users_state is defined) and (user.value.users_state == "present")) or
          user.value.users_state is not defined

    - name: "Debug the required groups for {{ user_member }}"
      ansible.builtin.debug:
        var: users_grp_mbrs
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}0{% else %}1{% endif %}

    - name: "Ensure that user is in the required groups for {{ user_member }}"
      ansible.builtin.user:
        name: "{{ user_member }}"
        groups: "{{ users_grp_mbrs }}"
        append: false
      register: user_member_changed

    - name: Debug user_member_changed
      ansible.builtin.debug:
        var: user_member_changed
        # verbosity: 2
      when:
        - user_member_changed is defined
        - user_member_changed.changed | ansible.builtin.bool

  tags:
    - users
...
