# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Groups configured
  block:

    # Get a list of all the users_groups for users present
    # Get a list of all the users listed in users_group_members present for users present
    # For each user present check that they exist and if they do ensure that their groups are set using usermod -G group1,group2 users1
    # For each user present check that they exist and if they do ensure that the users_group_members are in their group using usermod -G group1,group2 users1

    - name: Slurp /etc/passwd
      ansible.builtin.slurp:
        src: /etc/passwd
      register: users_etc_passwd_b64encoded

    - name: Set a fact for /etc/passwd
      ansible.builtin.set_fact:
        users_etc_passwd: "{{ users_etc_passwd_b64encoded['content'] | ansible.builtin.b64decode | community.general.jc('passwd') }}"

    - name: Debug users_etc_passwd
      ansible.builtin.debug:
        var: users_etc_passwd
        verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}"
      tags:
        - debug

    - name: Slurp /etc/group
      ansible.builtin.slurp:
        src: /etc/group
      register: users_etc_group_b64encoded

    - name: Set a fact for /etc/group
      ansible.builtin.set_fact:
        users_etc_group: "{{ users_etc_group_b64encoded['content'] | ansible.builtin.b64decode | community.general.jc('group') }}"

    - name: Debug users_etc_group
      ansible.builtin.debug:
        var: users_etc_group
        verbosity: "{% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}"
      tags:
        - debug

  tags:
    - users
...
