# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: User groups configured
  block:

    - name: "Set user_update_groups to an empty list for user {{ user_update }}"
      ansible.builtin.set_fact:
        user_update_groups: []

    - name: "Debug user_update_groups for user {{ user_update }}"
      ansible.builtin.debug:
        var: user_update
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}2{% else %}3{% endif %}
      tags:
        - debug

    - name: "Debug users_groups for user {{ user_update }}"
      ansible.builtin.debug:
        msg: "{{ users | ansible.builtin.dict2items | community.general.json_query(user_update_groups_jpq) }}"
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}1{% else %}2{% endif %}
      vars:
        user_update_groups_jpq: "[?key=='{{ user_update }}'].value.users_groups|[]"
      tags:
        - debug

    - name: "Add groups to user_update_groups for user {{ user_update }}"
      ansible.builtin.set_fact:
        user_update_groups: "{{ user_update_groups + (users | ansible.builtin.dict2items | community.general.json_query(user_update_groups_jpq)) }}"
      vars:
        user_update_groups_jpq: "[?key=='{{ user_update }}'].value.users_groups|[]"
      when:
        - users | ansible.builtin.dict2items | community.general.json_query(user_update_groups_jpq) is defined
        - users | ansible.builtin.dict2items | community.general.json_query(user_update_groups_jpq) != []
        - users | ansible.builtin.dict2items | community.general.json_query(user_update_groups_jpq) | ansible.builtin.type_debug =="list"

    - name: "Debug user_update_groups for user {{ user_update }}"
      ansible.builtin.debug:
        var: user_update_groups
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}2{% else %}3{% endif %}
      tags:
        - debug

    - name: "Debug users who have user {{ user_update }} listed in users_group_members"
      ansible.builtin.debug:
        msg: "User {{ user.key }} has user {{ user_update }} as one of their group members, their users_group_members are {{ user.value.users_group_members | ansible.builtin.join(', ') }}"
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}2{% else %}3{% endif %}
      loop: "{{ users | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: user
        label: "{{ user.key }}"
      when:
        - user.key != "root"
        - user.key in users_existing
        - >-
          ((user.value.users_state is not defined) or
          ((user.value.users_state is defined) and (user.value.users_state != "absent")))
        - (user.value.users_group_members is defined) and (user.value.users_group_members != [])
        - user_update in user.value.users_group_members
      tags:
        - debug

    - name: "Add users who have user {{ user_update }} listed in users_group_members to user_update_groups"
      ansible.builtin.set_fact:
        user_update_groups: "{{ user_update_groups + [user.key] }}"
      loop: "{{ users | ansible.builtin.dict2items }}"
      loop_control:
        loop_var: user
        label: "{{ user.key }}"
      when:
        - user.key != "root"
        - user.key in users_existing
        - >-
          ((user.value.users_state is not defined) or
          ((user.value.users_state is defined) and (user.value.users_state != "absent")))
        - (user.value.users_group_members is defined) and (user.value.users_group_members != [])
        - user_update in user.value.users_group_members

    - name: "Debug user_update_groups for user {{ user_update }}"
      ansible.builtin.debug:
        var: user_update_groups
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}2{% else %}3{% endif %}
      tags:
        - debug

    - name: "Ensure that user_update_groups is sorted and unique for user {{ user_update }}"
      ansible.builtin.set_fact:
        user_update_groups: "{{ user_update_groups | ansible.builtin.sort | ansible.builtin.unique }}"

    - name: "Debug user_update_groups for user {{ user_update }}"
      ansible.builtin.debug:
        var: user_update_groups
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}2{% else %}3{% endif %}
      tags:
        - debug

    - name: "User {{ user_update }} in groups {{ user_update_groups | ansible.builtin.join(', ') }}"
      ansible.builtin.user:
        name: "{{ user_update }}"
        groups: "{{ user_update_groups }}"
        append: false
      register: user_update_changed

    - name: Debug user_update_changed
      ansible.builtin.debug:
        var: user_update_changed
        verbosity: >-
          {% if ansible_check_mode | ansible.builtin.bool or ansible_diff_mode | ansible.builtin.bool %}2{% else %}3{% endif %}
      when:
        - user_update_changed is defined
        - user_update_changed.changed | ansible.builtin.bool
      tags:
        - debug

  tags:
    - users
...
