---
- debug:
    msg: "user={{ user }} group={{ group }}"
  loop: "{{ user.value.users_groups }}"
  loop_control:
    loop_var: group
    label: "{{ group }}" 
  tags:
    - users-update

- name: Add group
  group:
    name: "{{ group }}"
    state: present
  loop: "{{ user.value.users_groups }}"
    loop_var: group
    label: "{{ group }}" 
  tags:
    - users-update
...
