---
- name: Debug group
  ansible.builtin.debug:
    var: group
    verbosity: 2
  loop: "{{ user.value.users_groups }}"
  loop_control:
    loop_var: group
    label: "{{ group }}"
  tags:
    - users

- name: Add group
  ansible.builtin.group:
    name: "{{ group }}"
    state: present
  loop: "{{ user.value.users_groups }}"
  loop_control:
    loop_var: group
    label: "{{ group }}"
  tags:
    - users
...
