# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: HTTP Authentication tasks
  block:

    - name: Debug vhost
      ansible.builtin.debug:
        msg:
          - "user.value.users.home: {{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
          - "vhost.key: {{ vhost.key }}"
          - "vhost.value.users_apache_server_name: {{ vhost.value.users_apache_server_name }}"
        verbosity: 2

    - name: Debug users_apache_htauth_users loop
      ansible.builtin.debug:
        msg:
          - "htauth.name: {{ htauth.name }}"
          - "htauth.password: {{ htauth.password | default(omit) }}"
          - "htauth.state: {{ htauth.state | default('present') }}"
        verbosity: 2
      loop: "{{ vhost.value.users_apache_htauth_users }}"
      loop_control:
        loop_var: htauth
        label: "{{ htauth.name }}"

    - name: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.htpasswd directory present"
      ansible.builtin.file:
        path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.htpasswd"
        state: directory
        owner: root
        group: "{{ user.value.users_group | default(user.key) }}"
        mode: "0750"

    - name: "HTTP Authentication usernames and passwords for {{ vhost.value.users_apache_server_name }}"
      community.general.htpasswd:
        path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.htpasswd/{{ vhost.value.users_apache_server_name }}"
        name: "{{ htauth.name }}"
        password: "{{ htauth.password }}"
        state: "{{ htauth.state | default('present') }}"
        owner: root
        group: "{{ user.value.users_group | default(user.key) }}"
        mode: "0640"
      when:
        - htauth.password is defined and htauth.password | length > 0
        - htauth.state is not defined or htauth.state == "present"
      loop: "{{ vhost.value.users_apache_htauth_users }}"
      loop_control:
        loop_var: htauth
        label: "{{ htauth.name }}"

  tags:
    - users
...
