---
- name: "Stat {{ item.value.users_home | default('/home/' + item.key) }}/.my.cnf"
  stat:
    path: "{{ item.value.users_home | default('/home/' + item.key) }}/.my.cnf"
  register: users_mycnf

- block:

    - name: "Generate a random password for {{ item.key }} MaridaDB account as ~/.my.cnf doesn't exist"
      command: pwgen -n 20 1
      register: users_mariadb_password_gen

    - name: Set a fact for the mariadb_password
      set_fact:
        users_mariadb_password: "{{ users_mariadb_password_gen.stdout | trim | quote }}"

  when: users_mycnf.stat.exists == False

- block:

    - name: "MariaDB password read from {{ item.value.users_home | default('/home/' + item.key) }}/.my.cnf"
      shell: "my_print_defaults --defaults-file='{{ item.value.users_home | default('/home/' + item.key) }}/.my.cnf' client | grep '^--password' | sed -e 's/--password=//'"
      register: users_mariadb_password_read

    - name: Set a fact for the mariadb_password
      set_fact:
        users_mariadb_password: "{{ users_mariadb_password_read.stdout | trim | quote }}"

  when: users_mycnf.stat.exists == True

- debug:
    msg: "MariaDB passwd for {{ item.key }}: {{ users_mariadb_password }}"
    verbosity: 3

- fail:
    msg: "The mariadb_password appears not to be set"
  when: ( users_mariadb_password is not defined ) or ( users_mariadb_password == "" )

- name: "mariadb_password written to {{ users_mycnf }}"
  template:
    src: templates/my.cnf.j2
    dest: "{{ item.value.users_home | default('/home/' + item.key) }}/.my.cnf"
    owner: "{{ item.key }}"
    group: "{{ item.value.users_group | default(item.key) }}"
    mode: 0400
    force: true

- name: "The databases that {{ item.key }} has access to"
  command: mysql -B -N -e "SELECT Db FROM mysql.db WHERE User='{{ item.key }}';" mysql
  changed_when: false
  register: users_mariadb_list

- debug: 
    msg: "Databases that {{ item.key }} should have access to: {{ item.value.users_mariadb_databases }}"
    verbosity: 1

- debug:
    msg: "Databases that {{ item.key }} does have access to: {{ users_mariadb_list.stdout_lines }}"
    verbosity: 1

- debug:
    msg: "Databases to delete: {{ users_mariadb_list.stdout_lines | difference(item.value.users_mariadb_databases) }}"
    verbosity: 1
  when: ( users_mariadb_list is defined ) and ( users_mariadb_list != "" )

- set_fact:
    users_mariadb_delete_list: "{{ users_mariadb_list.stdout_lines | difference(item.value.users_mariadb_databases) }}"

- name: "Databases absent for {{ item.key }}"
  mysql_db:
    name: "{{ db }}"
    state: absent
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ users_mariadb_delete_list }}"
  when: ( users_mariadb_delete_list is defined ) and ( users_mariadb_delete_list != [] )
  loop_control:
    loop_var: db

- name: "Databases present for {{ item.key }}"
  mysql_db:
    name: "{{ db }}"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ item.value.users_mariadb_databases }}"
  loop_control:
    loop_var: db

- name: "Set a variable for mysql_user priv for {{ item.key }}"
  set_fact:
    users_mariadb_priv: "{% if item.value.users_mariadb_databases[0] is defined %}{% for db in item.value.users_mariadb_databases %}{{ db }}.*:ALL{% if not loop.last %}/{% endif %}{% endfor %}{% else %}*.*:USAGE{% endif %}"

- name: "Print priv for {{ item.key }}"
  debug:
    var: users_mariadb_priv
    verbosity: 1

- name: "MariaDB {{ item.key }} user present"
  mysql_user:
    name: "{{ item.key }}"
    password: "{{ users_mariadb_password }}"
    priv: "{{ users_mariadb_priv }}"
    state: present
    update_password: always
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
