# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: MariaDB tasks
  block:

    - name: Ensure that MariaDB user is present in /etc/passwd and /etc/group when a chroot is used
      block:

        - name: "Read mysql entry from /etc/passwd"
          ansible.builtin.command: "grep ^mysql: /etc/passwd"
          check_mode: false
          changed_when: false
          register: users_etc_passwd

        - name: "mysql present in {{ users_chroot_dir }}/etc/passwd"
          ansible.builtin.lineinfile:
            path: "{{ users_chroot_dir }}/etc/passwd"
            line: "{{ users_etc_passwd.stdout }}"
            state: present
            mode: "0644"
            owner: root
            group: root

        - name: "Read mysql entry from /etc/group"
          ansible.builtin.command: "grep ^mysql: /etc/group"
          check_mode: false
          changed_when: false
          register: users_etc_group

        - name: "mysql present in {{ users_chroot_dir }}/etc/group"
          ansible.builtin.lineinfile:
            path: "{{ users_chroot_dir }}/etc/group"
            line: "{{ users_etc_group.stdout }}"
            state: present
            mode: "0644"
            owner: root
            group: root

      when:
        - ( users_chroot is defined ) and ( users_chroot )
        - ( users_chroot_dir is defined )

  tags:
    - users
...
