---
# https://github.com/digitalist-se/userconsole#usercreate
- name: Include adduser tasks from Matomo role
  include_role:
    name: matomo
    tasks_from: adduser.yml
  vars:
    matomo_login: "{{ item.key }}"
    matomo_login_email: "{{ item.value.users_email }}"
    users_matomo_notify_passwd: "{{ item.value.users_matomo_notify_passwd | default(true) }}"
  tags:
    - users-update
