---
- name: Ensite that a Matomo site is present and correct
  block:

    - name: "Check if a Matomo ID exists for {{ vhost.value.users_apache_server_name }}"
      uri:
        url: "{{ matomo_url }}"
        method: POST
        body_format: form-urlencoded
        body:
          module: API
          format: JSON
          token_auth: anonymous
          method: SitesManager.getSitesIdFromSiteUrl
          url: "http://{{ vhost.value.users_apache_server_name }}"
          return_content: true
      register: users_matomo_get_sites_id_from_siteurl

    - name: Debug users_matomo_get_sites_id_from_siteurl
      debug:
        var: users_matomo_get_sites_id_from_siteurl
        verbosity: 2

    # - name: If [] returned then include site_present.yml tasks from Matomo role

    # - name: If id(s) returned then get corresponding URLs using SitesManager.getSiteUrlsFromId

    # - name: If URLs returned match then nothing needs doing

    # - name: If URLs don't match include site_present.yml tasks from Matomo role

  tags:
    - users
...
