# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Matomo tasks
  block:

    - name: Debug user
      ansible.builtin.debug:
        var: user
        verbosity: "{% if ansible_check_mode | bool or ansible_diff_mode | bool %}0{% else %}1{% endif %}"

    - name: Include Matomo user absent tasks
      ansible.builtin.include_tasks: matomo_user_absent.yml
      when:
        - user.value.users_state is defined
        - user.value.users_state == "absent"

    - name: Include Matomo user present tasks
      ansible.builtin.include_tasks: matomo_user_present.yml
      when:
        - user.key != "root"
        - ( "sudo" not in user.value.users_groups )
        - ( user.value.users_state is not defined ) or ( ( user.value.users_state is defined ) and ( user.value.users_state == "present" ) )
        - ( user.value.users_system is not defined ) or ( ( user.value.users_system is defined ) and ( not user.value.users_system | bool ) )
        - user.value.users_email is defined
        - ( ( user.value.users_matomo_account is defined ) and ( user.value.users_matomo_account | bool ) ) or ( user.value.users_matomo_account is not defined )

  tags:
    - users
...
