# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Matomo site tasks
  block:

    - name: "Debug matomo addsite for {{ user.key }}"
      ansible.builtin.debug:
        msg:
          - "matomo_site_name: {{ vhost.value.users_apache_server_name }}"
          - "matomo_site_main_url: http://{{ vhost.value.users_apache_server_name }}"
          - "matomo_site_urls: {% if vhost.value.users_apache_server_aliases is defined %}{{ vhost.value.users_apache_server_aliases | map('regex_replace', '^(.*)$', 'http://\\1') | list }}{% else %}[]{% endif %}"
          - "matomo_login: {{ user.key }}"
          - "matomo_login_email: {{ user.value.users_email }}"
          - "users_cms: {{ vhost.value.users_cms | default('') }}"
        verbosity: 1
      when:
        - ( vhost.value.users_matomo_site is not defined ) or ( vhost.value.users_matomo_site is defined and vhost.value.users_matomo_site )
        - ( vhost.value.users_cms is not defined ) or ( vhost.value.users_cms is not regex('^matomo|phpmyadmin|nextcloud|kimai$') )
      loop: "{{ user.value.users_apache_virtual_hosts | dict2items }}"
      loop_control:
        loop_var: vhost
        label: "{{ vhost.key }}"

    - name: "Matomo sites present for {{ user.key }}"  # noqa: var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: matomo
        tasks_from: site_present.yml
      when:
        - ( vhost.value.users_matomo_site is not defined ) or ( vhost.value.users_matomo_site is defined and vhost.value.users_matomo_site )
        - ( vhost.value.users_cms is not defined ) or ( vhost.value.users_cms is not regex('^matomo|phpmyadmin|nextcloud|kimai$') )
      loop: "{{ user.value.users_apache_virtual_hosts | dict2items }}"
      loop_control:
        loop_var: vhost
        label: "{{ vhost.key }}"
      vars:
        matomo_login: "{{ user.key }}"
        matomo_login_email: "{{ user.value.users_email }}"
        matomo_site_name: "{{ vhost.value.users_apache_server_name }}"
        matomo_site_main_url: "http://{{ vhost.value.users_apache_server_name }}"
        # https://gist.github.com/halberom/b1f6eaed16dba1b298e8#gistcomment-2706913
        matomo_site_urls: "{% if vhost.value.users_apache_server_aliases is defined %}{{ vhost.value.users_apache_server_aliases | map('regex_replace', '^(.*)$', 'http://\\1') | list }}{% else %}[]{% endif %}"

  when:
    - ( user.key != "root" )
    - ( user.value.users_matomo_account is defined ) and ( user.value.users_matomo_account | bool )
    - ( user.value.users_email is defined )
    - ( matomo_user is defined ) and ( matomo_user | length > 0 )
    - ( matomo_password is defined ) and ( matomo_password | length > 0 )
    - ( matomo_token_auth is defined ) and ( matomo_token_auth | length > 0 )
    - matomo_user in ansible_facts.getent_passwd.keys()
    - user_matomo_config.stat.exists
    - ( matomo_installed is defined ) and ( matomo_installed is version('3.14.1', '>=') )
    - ( matomo_super_user_access is defined ) and ( matomo_super_user_access )
  tags:
    - users
...
