---
# https://github.com/digitalist-se/userconsole#userdelete
- name: "Include deleteuser tasks from Matomo role for {{ user.key }}"
  ansible.builtin.include_role:
    name: matomo
    tasks_from: deleteuser.yml
  vars:
    matomo_login: "{{ user.key }}"
  tags:
    - users
...
