# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: "Stat {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.notify_passwd file"
  ansible.builtin.stat:
    path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.notify_passwd"
  register: users_notify_passwd_file
  tags:
    - users

- name: Notify password
  block:

    - name: "Random passwd for {{ user.key }} generated"
      ansible.builtin.command: "pwgen -n {{ 30 | random(20) }} 1"
      no_log: true
      register: users_passwd

    - name: "SHA 512 hash of passwd generated"
      ansible.builtin.command: "mkpasswd --method=sha-512 {{ users_passwd.stdout }}"
      no_log: true
      register: users_passwd_hash

    - name: "Password set for {{ user.key }}"
      ansible.builtin.user:
        name: "{{ user.key }}"
        password: "{{ users_passwd_hash.stdout }}"

    - name: "Password notification email sent to {{ user.value.users_email }}"
      community.general.mail:
        from: "{{ users_notify_from | default('Webarchitects') | quote }} <root@{{ inventory_hostname }}>"
        to: "{{ user.value.users_name | default(user.key) | quote }} <{{ user.value.users_email }}>"
        subject: "[{{ users_notify_subject_tag | default('webarchitects') }}] SFTP / SSH Password for {{ user.key }} on {{ inventory_hostname }}"
        headers: "{{ users_notify_headers }}"
        charset: us-ascii
        body: "{{ lookup('template', 'notify_passwd.j2') }}"
        host: localhost
        port: 25
        secure: never
      when:
        - user.value.users_email is defined
        - user.value.users_email | length > 0

    - name: "Notification date recorded in {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.notify_passwd file"
      ansible.builtin.lineinfile:
        path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.notify_passwd"
        line: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }} : {{ user.value.users_name | default(user.key) }} <{{ user.value.users_email }}>"
        create: true
        state: present
        insertafter: EOF
        owner: root
        group: "{{ user.key }}"
        mode: "0640"

  when: not users_notify_passwd_file.stat.exists | bool
  tags:
    - users
...
