---
- name: "Stat {{ item.value.users_home | default('/home/' + item.key) }}/.notify_passwd file"
  stat:
    path: "{{ item.value.users_home | default('/home/' + item.key) }}/.notify_passwd"
  register: users_notify_passwd_file

- block:

    - name: "Random passwd for {{ item.key }} generated"
      command: pwgen -n 20 1
      register: users_passwd

    - name: "SHA 512 hash of passwd generated"
      command: "mkpasswd --method=sha-512 {{ users_passwd.stdout }}"
      register: users_passwd_hash

    # https://www.systutorials.com/39549/changing-linux-users-password-in-one-command-line/
    #- name: "Password set for {{ item.key }}"
    #  shell: |
    #         echo -e "{{ users_passwd.stdout }}
    #         {{ users_passwd.stdout }}" | sed 's/^ //' | passwd {{ item.key }}
    #  register: users_passwd_change

    - name: "Password set for {{ item.key }}"
      user:
        name: "{{ item.key }}"
        password: "{{ users_passwd_hash.stdout }}"

    #- debug:
    #    msg: "{{ users_passwd_change.stdout }]"
    #    verbosity: 1

    - name: "Password notification email sent to {{ item.value.users_email }}"
      mail:
        from: "{{ users_passwd_notify_from | default('Webarchitects <root@{{ ansible_hostname }}') }}"
        to: "{{ users_name }} <{{ item.value.users_email }}>" 
        subject: "[{{ users_passwd_notify_subject_tag | default('webarchitects') }}] SFTP / SSH Password for {{ item.key }} on {{ ansible_hostname }}"
        body: "{{ lookup('template', 'templates/notify_passwd.j2') }}"
        host: localhost
        port: 25
      when: item.value.users_email is defined and item.value.users_email != ""

    - name: "Notification date recorded in {{ item.value.users_home | default('/home/' + item.key) }} file"
      lineinfile:
        path: "{{ item.value.users_home | default('/home/' + item.key) }}"
        line: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S')}} : {{ users_name }} <{{ item.value.users_email }}>"
        create: yes
        state: present
        insertafter: EOF
        owner: root
        group: root
        mode: 0644

  when: users_notify_passwd_file.stat.exists == False
