---
- name: "Stat {{ item.value.users_home | default('/home/' + item.key) }}/.notify_passwd file"
  stat:
    path: "{{ item.value.users_home | default('/home/' + item.key) }}/.notify_passwd"
  register: users_notify_passwd_file

- block:

    - name: "Random passwd for {{ item.key }} generated"
      command: pwgen -n 20 1
      register: users_passwd

    - name: "SHA 512 hash of passwd generated"
      command: "mkpasswd --method=sha-512 {{ users_passwd.stdout }}"
      register: users_passwd_hash

    - name: "Password set for {{ item.key }}"
      user:
        name: "{{ item.key }}"
        password: "{{ users_passwd_hash.stdout }}"

    - name: "Password notification email sent to {{ item.value.users_email }}"
      mail:
        from: "{{ users_notify_passwd_from | default('Webarchitects') }} <root@{{ ansible_fqdn }}>"
        to: "{{ item.value.users_name | default(item.key) }} <{{ item.value.users_email }}>"
        subject: "[{{ users_passwd_notify_subject_tag | default('webarchitects') }}] SFTP / SSH Password for {{ item.key }} on {{ ansible_fqdn }}"
        headers:
          - "{{ users_notify_passwd_headers | default['Reply-To=Webarchitects <support@webarchitects.coop>'] }}"
        body: "{{ lookup('template', 'templates/notify_passwd.j2') }}"
        host: localhost
        port: 25
        secure: never
      when: item.value.users_email is defined and item.value.users_email != ""

    - name: "Notification date recorded in {{ item.value.users_home | default('/home/' + item.key) }}/.notify_passwd file"
      lineinfile:
        path: "{{ item.value.users_home | default('/home/' + item.key) }}/.notify_passwd"
        line: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S')}} : {{ item.value.users_name | default(item.key) }} <{{ item.value.users_email }}>"
        create: true
        state: present
        insertafter: EOF
        owner: root
        group: root
        mode: 0640

  when: users_notify_passwd_file.stat.exists == False
