---
- name: pam-mysql present
  apt:
    pkg:
      - pam-mysql
  state: present
  update_cache: false

- name: /etc/pam-mysql.conf in place
  copy:
    src: files/pam-mysql/pam-mysql.conf
    dest: /etc/pam-mysql.conf
  mode: 0640
  owner: root
  group: root

- name: /etc/pam.d/ files in place
  copy:
    src: "files/pam-mysql/{{ item }}"
    dest: "/etc/pam.d/{{ item }}"
  mode: 0644
  owner: root
  group: root
  loop:
    - common-account
    - common-auth
