# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Remove PHP-FPM pool.d file and restart service
  block:

    - name: "Check if /etc/php/{{ users_phpfpm_ver }}/fpm/pool.d/{{ user.key }}.conf is present"
      ansible.builtin.stat:
        path: "/etc/php/{{ users_phpfpm_ver }}/fpm/pool.d/{{ user.key }}.conf"
      register: users_phpfpm_pool_file

    - name: "PHP FPM pool.d file absent for {{ user.key }}"
      ansible.builtin.file:
        path: "/etc/php/{{ users_phpfpm_ver }}/fpm/pool.d/{{ user.key }}.conf"
        state: absent
      register: users_phpfpm_pool_absent

    - name: PHP FPM conditional restart
      block:

        - name: "PHP FPM configtest for version {{ users_phpfpm_ver }}"
          ansible.builtin.command: "php-fpm{{ users_phpfpm_ver }} --test"
          register: users_phpfpm_pool_configtest

        - name: "PHP FPM restarted for version {{ users_phpfpm_ver }}"
          ansible.builtin.service:
            name: "php{{ users_phpfpm_ver }}-fpm"
            state: restarted
          when: ( "test is successful" in users_phpfpm_pool_configtest.stderr )

      when:
        - users_phpfpm_pool_absent.changed is defined
        - users_phpfpm_pool_absent.changed | bool

  tags:
    - users
...
