---
- name: Set the PHP version variable on stretch
  set_fact:
    users_phpfpm_version: "7.0"
  when: users_debian_version == "stretch"

- name: Set the PHP version variable on buster
  set_fact:
    users_phpfpm_version: "7.3"
  when: users_debian_version == "buster"

- name: Set the PHP version variable on bionic
  set_fact:
    users_phpfpm_version: "7.2"
  when: users_debian_version == "buster"

- name: Get all groups
  getent:
    database: group
    split: ':'

- debug:
    var: getent_group
    verbosity: 2

- block:

    - name: Users PHP FPM pool.d file absent
      file:
        path: "/etc/php/{{ users_phpfpm_version }}/fpm/pool.d/{{ item.key }}.conf"
        state: absent
      loop: "{{ users | dict2items }}"
      when: ( item.value.users_state is defined and item.value.users_state == "absent" ) or ( "phpfpm" not in item.value.users_groups or "chroot" not in item.value.users_groups )

    - name: "php-fpm log directory {{ item.value.users_home | default('/home/' + item.key) }}/logs present"
      file:
        path: "{{ item.value.users_home | default('/home/' + item.key) }}/logs"
        state: directory
        owner: root
        group: "{{ item.key }}"
        mode: 0750
      loop: "{{ users | dict2items }}"
      when: ( item.value.users_state is undefined or item.value.users_state == "present" ) and ( "phpfpm" in item.value.users_groups and "chroot" in item.value.users_groups )

    - name: Users PHP FPM pool.d file present
      template:
        src: templates/phpfpm_chroot_user.conf.j2
        dest: "/etc/php/{{ users_phpfpm_version }}/fpm/pool.d/{{ item.key }}.conf"
      loop: "{{ users | dict2items }}"
      when: ( item.value.users_state is undefined or item.value.users_state == "present" ) and ( "phpfpm" in item.value.users_groups and "chroot" in item.value.users_groups )

  when: ( users_phpfpm_version is defined ) and ( "phpfpm" in getent_group and "chroot" in getent_group )

- name: Restart php-fpm
  service:
    name: "php{{ users_phpfpm_version }}-fpm"
    state: restarted
