---
- name: PHP-FPM chroot logrotation config in place
  template:
    src: templates/phpfpm_users_logrotate.j2
    dest: /etc/logrotate.d/phpfpm_users_logrotate
    owner: root
    group: root
    mode: 0644
  tags:
    - phpfpm
    - logrotate
    - users-chroot

- name: /etc/apache2/localhost.d present
  file:
    path: /etc/apache2/localhost.d
    state: directory
  when: users_apache2.stat.exists
  tags:
    - users-update
    - users-chroot
    - phpfpm

- name: /etc/nginx/localhost.d present
  file:
    path: /etc/nginx/localhost.d
    state: directory
  when: users_nginx.stat.exists
  tags:
    - users-update
    - users-chroot
    - phpfpm
...
