---
- name: PHP-FPM chroot logrotation config in place
  template:
    src: phpfpm_users_logrotate.j2
    dest: /etc/logrotate.d/phpfpm_users_logrotate
    mode: 0644
    owner: root
    group: root
  tags:
    - users

- name: /etc/apache2/localhost.d present
  file:
    path: /etc/apache2/localhost.d
    state: directory
    mode: 0755
    owner: root
    group: root
  when: ( "apache2" in ansible_facts.packages )
  tags:
    - users

- name: /etc/nginx/localhost.d present
  file:
    path: /etc/nginx/localhost.d
    state: directory
    mode: 0755
    owner: root
    group: root
  when: ( "nginx" in ansible_facts.packages )
  tags:
    - users
...
