---
# setquota ${USERNAME} ${SQUOTA} ${DQUOTA} 0 0 -a
#
- debug:
    msg: "quota: {{ item.value.users_quota }}"

#- name: set a variable for the block-softlimit as 90% of users_quota in kibibytes
#  #shell: "echo '{{ ( item.value.users_quota ) | human_to_bytes }} / 1024 / 100 * 90' | bc"
#  shell: "echo '{{ ( item.value.users_quota ) | human_to_bytes / 1024 / 100 * 90 }}'"
#  register: quota_block_softlimit
#
#- name: set a variable for the block-hardlimit as users_quota in kibibytes
#  shell: "echo '{{ ( item.value.users_quota ) | human_to_bytes }} / 1024' | bc"
#  register: quota_block_hardlimit

# https://superuser.com/a/1156454
- name: Set a variables for quota
  set_fact:
    #quota_block_softlimit: "{{ ((( item.value.users_quota | human_to_bytes ) / 1024 ) // 100 ) * 90 | round(0, 'floor') | int }}"
    # https://stackoverflow.com/a/35158145
    quota_block_softlimit: "{{ ( item.value.users_quota | human_to_bytes ) // 1125 }}"
    quota_block_hardlimit: "{{ ( item.value.users_quota | human_to_bytes ) // 1024 }}"
    quota_inode_softlimit: "{{ ( item.value.users_quota | human_to_bytes ) // 2248 }}"
    quota_inode_hardlimit: "{{ ( item.value.users_quota | human_to_bytes ) // 2048 }}"

- debug:
    msg: 
    - "block-softlimit: {{ quota_block_softlimit }}"
    - "block-hardlimit: {{ quota_block_hardlimit }}"
    - "inode-softlimit: {{ quota_inode_softlimit }}"
    - "inode-hardlimit: {{ quota_inode_hardlimit }}"

#block-hardlimit
#inode-softlimit
#inode-hardlimit

- name: setquota
  #command: "echo 'setquota -b {{ item.key }} {{ quota_block_softlimit }} {{ quota_block_hardlimit }} {{ quota_inode_softlimit }} {{ quota_inode_hardlimit }} {{ quota_dir }}'" 
  command: "setquota -b {{ item.key }} {{ quota_block_softlimit }} {{ quota_block_hardlimit }} {{ quota_inode_softlimit }} {{ quota_inode_hardlimit }} {{ quota_dir }}" 
#  command: "setquota {{ item.key }} {{ ( item.value.users_quota | int ) | human_to_bytes(default_unit=k) / 100 * 90 }}
