# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
# https://superuser.com/a/1156454
# https://stackoverflow.com/a/35158145

- name: "Set the disk quota for {{ user.key }}"
  block:

    - name: "Set users_quota_block_softlimit from users_quota_block_softlimit for {{ user.key }}"
      ansible.builtin.set_fact:
        users_quota_block_softlimit: "{{ user.value.users_quota_block_softlimit }}"
      check_mode: false
      when: user.value.users_quota_block_softlimit is defined

    - name: "Set users_quota_block_softlimit from users_quota for {{ user.key }}"
      ansible.builtin.set_fact:
        # softlimit 10% under hardlimit:
        users_quota_block_softlimit: "{{ (user.value.users_quota | human_to_bytes) // 1125 }}"
      check_mode: false
      when: user.value.users_quota_block_softlimit is not defined

    - name: "Set users_quota_block_hardlimit from users_quota_block_hardlimit for {{ user.key }}"
      ansible.builtin.set_fact:
        users_quota_block_hardlimit: "{{ user.value.users_quota_block_hardlimit }}"
      check_mode: false
      when: user.value.users_quota_block_hardlimit is defined

    - name: "Set users_quota_block_hardlimit from users_quota for {{ user.key }}"
      ansible.builtin.set_fact:
        users_quota_block_hardlimit: "{{ (user.value.users_quota | human_to_bytes) // 1024 }}"
      check_mode: false
      when: user.value.users_quota_block_hardlimit is not defined

    - name: "Set users_quota_inode_softlimit from users_quota_inode_softlimit for {{ user.key }}"
      ansible.builtin.set_fact:
        users_quota_inode_softlimit: "{{ user.value.users_quota_inode_softlimit }}"
      check_mode: false
      when: user.value.users_quota_inode_softlimit is defined

    - name: "Set users_quota_inode_softlimit from users_quota for {{ user.key }}"
      ansible.builtin.set_fact:
        # softlimit 10% under hardlimit:
        users_quota_inode_softlimit: "{{ (user.value.users_quota | human_to_bytes) // 5625 }}"
      check_mode: false
      when: user.value.users_quota_inode_softlimit is not defined

    - name: "Set users_quota_inode_hardlimit from users_quota_inode_hardlimit for {{ user.key }}"
      ansible.builtin.set_fact:
        users_quota_inode_hardlimit: "{{ user.value.users_quota_inode_hardlimit }}"
      check_mode: false
      when: user.value.users_quota_inode_hardlimit is defined

    - name: "Set users_quota_inode_hardlimit from users_quota for {{ user.key }}"
      ansible.builtin.set_fact:
        users_quota_inode_hardlimit: "{{ (user.value.users_quota | human_to_bytes) // 5120 }}"
      check_mode: false
      when: user.value.users_quota_inode_hardlimit is not defined

    - name: Print the quota variables that have just been set
      ansible.builtin.debug:
        msg:
          - "quota: {{ user.value.users_quota }}"
          - "block-softlimit: {{ users_quota_block_softlimit }}"
          - "block-hardlimit: {{ users_quota_block_hardlimit }}"
          - "inode-softlimit: {{ users_quota_inode_softlimit }}"
          - "inode-hardlimit: {{ users_quota_inode_hardlimit }}"
        verbosity: 2
      check_mode: false
      tags:
        - debug

    - name: Set facts for lookups on the existing limits
      ansible.builtin.set_fact:
        users_quota_existing_block_softlimit_lookup: "{{ user.key }} file=/tmp/{{ inventory_hostname }}/{{ quota_dir }}/quota_user.csv delimiter=, col=4"
        users_quota_existing_block_hardlimit_lookup: "{{ user.key }} file=/tmp/{{ inventory_hostname }}/{{ quota_dir }}/quota_user.csv delimiter=, col=5"
        users_quota_existing_inode_softlimit_lookup: "{{ user.key }} file=/tmp/{{ inventory_hostname }}/{{ quota_dir }}/quota_user.csv delimiter=, col=8"
        users_quota_existing_inode_hardlimit_lookup: "{{ user.key }} file=/tmp/{{ inventory_hostname }}/{{ quota_dir }}/quota_user.csv delimiter=, col=9"
      check_mode: false

    - name: Set facts for the existing limits
      ansible.builtin.set_fact:
        users_quota_existing_block_softlimit: "{{ lookup('csvfile', users_quota_existing_block_softlimit_lookup) }}"
        users_quota_existing_block_hardlimit: "{{ lookup('csvfile', users_quota_existing_block_hardlimit_lookup) }}"
        users_quota_existing_inode_softlimit: "{{ lookup('csvfile', users_quota_existing_inode_softlimit_lookup) }}"
        users_quota_existing_inode_hardlimit: "{{ lookup('csvfile', users_quota_existing_inode_hardlimit_lookup) }}"
      check_mode: false

    - name: "The set quota command which is about to be run for {{ user.key }}"
      ansible.builtin.debug:
        msg:
          - "setquota {{ user.key }} {{ users_quota_block_softlimit }} {{ users_quota_block_hardlimit }} {{ users_quota_inode_softlimit }} {{ users_quota_inode_hardlimit }} {{ quota_dir }}"
        verbosity: 2
      tags:
        - debug

    - name: "Setquota for {{ user.key }}"
      ansible.builtin.command: "setquota {{ user.key }} {{ users_quota_block_softlimit }} {{ users_quota_block_hardlimit }} {{ users_quota_inode_softlimit }} {{ users_quota_inode_hardlimit }} {{ quota_dir }}"
      changed_when: ( users_quota_existing_block_softlimit != users_quota_block_softlimit ) or ( users_quota_existing_block_hardlimit != users_quota_block_hardlimit ) or ( users_quota_existing_inode_softlimit != users_quota_inode_softlimit ) or ( users_quota_existing_inode_hardlimit != users_quota_inode_hardlimit )

  tags:
    - users
...
