---
- debug:
    msg: 

# https://superuser.com/a/1156454
# https://stackoverflow.com/a/35158145

- name: Set quota_block_softlimit from users_quota_block_softlimit
  set_fact:
    quota_block_softlimit: "{{ item.value.users_quota_block_softlimit }}"
  when: item.value.users_quota_block_softlimit is defined

- name: Set quota_block_softlimit from users_quota
  set_fact:
    quota_block_softlimit: "{{ ( item.value.users_quota | human_to_bytes ) // 1125 }}"
  when: item.value.users_quota_block_softlimit is not defined

- name: Set quota_block_hardlimit from users_quota_block_hardlimit
  set_fact:
    quota_block_hardlimit: "{{ users_quota_block_hardlimit }}"
  when: item.value.users_quota_block_hardlimit is defined

- name: Set quota_block_hardlimit from users_quota
  set_fact:
    quota_block_hardlimit: "{{ item.value.users_quota | human_to_bytes ) // 1024 }}"
  when: item.value.users_quota_block_hardlimit is not defined

- name: Set quota_inode_softlimit from users_quota_inode_softlimit
  set_fact:
    quota_inode_softlimit: "{{ item.value.users_quota_inode_softlimit }}"
  when: item.value.users_quota_inode_softlimit is defined

- name: Set quota_inode_softlimit from users_quota
  set_fact:
    quota_inode_softlimit: "{{ item.value.users_quota | human_to_bytes ) // 225280 }}"
  when: item.value.users_quota_inode_softlimit is not defined

- name: Set quota_inode_hardlimit from users_quota_inode_hardlimit
  set_fact:
    quota_inode_hardlimit: "{{ users_quota_inode_hardlimit }}"
  when: item.value.users_quota_inode_hardlimit is defined

- name: Set quota_inode_hardlimit from users_quota
  set_fact:
    quota_inode_hardlimit: "{{ item.value.users_quota | human_to_bytes ) // 204800 }}"
  when: item.value.users_quota_inode_hardlimit is not defined
  
- debug:
    msg:
    - "quota: {{ item.value.users_quota }}"
    - "block-softlimit: {{ quota_block_softlimit }}"
    - "block-hardlimit: {{ quota_block_hardlimit }}"
    - "inode-softlimit: {{ quota_inode_softlimit }}"
    - "inode-hardlimit: {{ quota_inode_hardlimit }}"
    verbosity: 1

- name: setquota
  command: "setquota {{ item.key }} {{ quota_block_softlimit }} {{ quota_block_hardlimit }} {{ quota_inode_softlimit }} {{ quota_inode_hardlimit }} {{ quota_dir }}" 
