---
- debug:
    msg: 

# https://superuser.com/a/1156454
- name: Set a variables for quota
  set_fact:
    # https://stackoverflow.com/a/35158145
    quota_block_softlimit: "{{ users_quota_block_softlimit | default('( item.value.users_quota | human_to_bytes ) // 1125 ') }}"
    quota_block_hardlimit: "{{ users_quota_block_hardlimit | default('( item.value.users_quota | human_to_bytes ) // 1024 ') }}"
    quota_inode_softlimit: "{{ users_quota_inode_softlimit | default('( item.value.users_quota | human_to_bytes ) // 225280 ') }}"
    quota_inode_hardlimit: "{{ users_quota_inode_hardlimit | default('( item.value.users_quota | human_to_bytes ) // 204800 ') }}"

- debug:
    msg:
    - "quota: {{ item.value.users_quota }}"
    - "block-softlimit: {{ quota_block_softlimit }}"
    - "block-hardlimit: {{ quota_block_hardlimit }}"
    - "inode-softlimit: {{ quota_inode_softlimit }}"
    - "inode-hardlimit: {{ quota_inode_hardlimit }}"
    verbosity: 1

- name: setquota
  command: "setquota {{ item.key }} {{ quota_block_softlimit }} {{ quota_block_hardlimit }} {{ quota_inode_softlimit }} {{ quota_inode_hardlimit }} {{ quota_dir }}" 
