---
- name: Skel www files in place
  copy:
    src: "files/skel.d/www/{{ item }}"
    dest: "/usr/local/etc/skel.d/www/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - .bash_logout
    - .bashrc
    - .profile

- name: Skel www files touched
  file:
    path: "/usr/local/etc/skel.d/www/{{ item }}"
    state: touch
  with_items:
    - .bash_history
    - .yarnrc

- name: Skel www private directories present 
  file:
    path: "/usr/local/etc/skel.d/www/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - .cache
    - .composer
    - .config
    - .drush
    - .git
    - .gnupg
    - .npm
    - .ssh
    - .vim
    - .wp-cli
    - .yarn
    - logs
    - private
    - tmp

#- name: Skel files chowned
#  file:
#    path: /usr/local/etc/skel.d
#    state: directory
#    owner: root
#    group: root
#    recurse: true
