---
- name: "Skel {{ users_skeleton }} directory present"
  file:
    path: "/usr/local/etc/skel.d/{{ users_skeleton }}"
    state: directory

- name: "Skel {{ users_skeleton }} files in place"
  copy:
    src: "files/skel.d/{{ users_skeleton }}/{{ item }}"
    dest: "/usr/local/etc/skel.d/{{ users_skeleton }}/{{ item }}"
    owner: root
    group: root
    mode: 0600
  loop:
    - .bash_logout
    - .bashrc
    - .profile

- name: "Skel {{ users_skeleton }} files touched"
  file:
    path: "/usr/local/etc/skel.d/{{ users_skeleton }}/{{ item }}"
    state: touch
    owner: root
    group: root
    mode: 0600
    modification_time: preserve
    access_time: preserve
  with_items:
    - .bash_history
    - .yarnrc

- name: "Skel {{ users_skeleton }} private directories present"
  file:
    path: "/usr/local/etc/skel.d/{{ users_skeleton }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - .cache
    - .composer
    - .config
    - .drush
    - .git
    - .gnupg
    - .npm
    - .ssh
    - .vim
    - .wp-cli
    - .yarn
    - logs
    - private
    - sites
    - tmp
