---
- name: Check which shells are present
  shell: cat /etc/shells | grep -v ^#
  check_mode: false
  changed_when: false
  register: users_shells_check

- name: Array set for shells
  set_fact:
    users_shells: "{{ users_shells_check.stdout_lines | list }}"

- name: Print available shells
  debug:
    msg: "Available shells: {{ users_shells }}"
    verbosity: 2

- name: Get all groups
  getent:
    database: group
    split: ':'

- debug:
    var: getent_group
    verbosity: 2

- name: Get all users
  getent:
    database: passwd
    split: ':'

- debug:
    var: getent_passwd
    verbosity: 2
...
