---
- name: Check which shells are present
  shell: cat /etc/shells | grep -v ^#
  check_mode: false
  changed_when: false
  register: users_shells_check

- name: Array set for shells
  set_fact:
    users_shells: "{{ users_shells_check.stdout_lines | list }}"

- name: Print available shells
  debug:
    msg: "Available shells: {{ users_shells }}"
    verbosity: 2

- name: Get all groups
  getent:
    database: group
    split: ':'

- debug:
    var: getent_group
    verbosity: 2

- name: Get all users
  getent:
    database: passwd
    split: ':'

- debug:
    var: getent_passwd
    verbosity: 2

- name: Set a fact for the Debian version
  set_fact:
    users_debian_version: "{{ ansible_distribution_release }}"
  tags:
    - apache
    - letsencrypt
    - logrotate
    - phpfpm
    - users-update
    - users-cron
    - users-mariadb
    - users-scripts
    - users-quota
    - users-fstab
    - wordpress
    - matomo
    - phpmyadmin

- name: Load package information as facts
  package_facts:
    manager: apt
  tags:
    - apache
    - letsencrypt
    - logrotate
    - phpfpm
    - users-update
    - users-cron
    - users-mariadb
    - users-scripts
    - users-quota
    - users-fstab
    - wordpress
    - matomo
    - phpmyadmin

- name: Fail if ansible_facts.packages is not defined or empty
  fail:
    msg: The package_facts array is empty, this could be a result of the Ansible 2.8.x bug https://github.com/ansible/ansible/issues/56921
  when: ( ansible_facts.packages is not defined ) or ( ansible_facts.packages == [] )
  tags:
    - apache
    - letsencrypt
    - logrotate
    - phpfpm
    - users-update
    - users-cron
    - users-mariadb
    - users-scripts
    - users-quota
    - users-fstab
    - wordpress
    - matomo
    - phpmyadmin

- name: PHP FPM checks
  block:

    - name: Check if php-fpm is installed
      shell: "dpkg -s php{% if users_debian_version == 'stretch' %}7.0{% elif users_debian_version == 'buster' %}7.3{% elif users_debian_version == 'bionic' %}7.2{% endif %}-fpm | grep ^Status | awk '{ print $4 }'"
      register: users_phpfpm_status
      check_mode: false
      changed_when: false
      tags:
        - logrotate
        - phpfpm
        - users-update

    - name: php-fpm variable set
      block:

        - name: Print the users_phpfpm_status
          debug:
            msg: "users_phpfpm_status: {{ users_phpfpm_status.stdout }}"
            verbosity: 1
          tags:
            - logrotate
            - phpfpm
            - users-update

        - name: Set a fact for the PHP-FPM version
          set_fact:
            users_phpfpm_version: "{% if users_debian_version == 'stretch' %}7.0{% elif users_debian_version == 'buster' %}7.3{% elif users_debian_version == 'bionic' %}7.2{% endif %}"
          when: users_phpfpm_status.stdout == "installed"
          tags:
            - logrotate
            - phpfpm
            - users-update

      when: ( users_phpfpm_status is defined ) and ( users_phpfpm_status != "" )

  when: ( users_phpfpm is defined ) and ( users_phpfpm == True )

- name: Check if a chroot exists
  stat:
    path: "{{ chroot_dir | default('/chroot') }}"
  register: users_chroot_dir
  when: ( users_chroot is defined ) and ( users_chroot == True )
  tags:
    - logrotate
    - phpfpm
    - users-update
    - users-chroot
    - users-cron
    - users-fstab
...
