---
- name: Directories for users state files present
  file:
    path: "{{ users_state_dir }}/{{ dir }}"
    state: directory
  loop:
    - current
    - previous
    - proposed
  loop_control:
    loop_var: dir

- name: Proposed users state files present
  template:
    src: user_state.yml.j2
    dest: "{{ users_state_dir }}/proposed/{{ user.key }}.yml"
  check_mode: false
  register: users_state_file
  loop: "{{ users | dict2items }}"
  loop_control:
    loop_var: user
    label: "{{ user.key }}"

- name: Debug print the state template results
  debug:
    var: users_state_file

- name: Set an empty users_update array
  set_fact:
    users_update: []

- name: Check users current state files
  include_tasks: user_state.yml
  loop: "{{ users | dict2items }}"
  loop_control:
    loop_var: user

- name: Print the users to update
  debug:
    msg: "User to update: {{ users_update }}"
    verbosity: 2
...
