---
# Cron regular expressions copied from
# https://stackoverflow.com/questions/14203122/create-a-regular-expression-for-cron-statement
# NOTE that many things will fail like MON and FEB, this needs improvement or scrapping!
- name: Check the values in the user_cron_jobs array
  block:

    - name: Ensure that a name is defined for the cron job
      assert:
        that:
          - job.name is defined
          - job.name | type_debug is regex('^(str|AnsibleUnicode|AnsibleUnsafeText)$')

    - name: Ensure that the state is present or absent if defined for the cron job
      assert:
        that:
          - job.state is regex('^(absent|present)$')
      when: job.state is defined

    - name: Ensure that disabled is true or false if defined for the cron job
      assert:
        that:
          - job.state is | type_debug == "bool"
      when: job.disabled is defined

    - name: Ensure that the special_time for the cron job is valid if defined
      assert:
        that:
          - job.special_time is regex('^@(annually|yearly|monthly|weekly|daily|hourly|reboot)$')
      when: job.special_time is defined

    - name: Ensure that the minute for the cron job is valid if defined
      assert:
        that:
          - job.minute is regex('^(\*|([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])|\*\/([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]))$')
      when: job.minute is defined

    - name: Ensure that the hour for the cron job is valid if defined
      assert:
        that:
          - job.hour is regex('^(\*|([0-9]|1[0-9]|2[0-3])|\*\/([0-9]|1[0-9]|2[0-3]))$')
      when: job.hour is defined

    - name: Ensure that the day for the cron job is valid if defined
      assert:
        that:
          - job.day is regex('^(\*|([1-9]|1[0-9]|2[0-9]|3[0-1])|\*\/([1-9]|1[0-9]|2[0-9]|3[0-1]))$')
      when: job.day is defined

    - name: Ensure that the month for the cron job is valid if defined
      assert:
        that:
          - job.month is regex('^(\*|([1-9]|1[0-2]?)(-([1-9]|1[0-2]?))?)(\/[1-9][0-9]*)?(,(\*|([1-9]|1[0-2]?)(-([1-9]|1[0-2]?))?)(\/[1-9][0-9]*)?)*$')
      when: job.month is defined

    - name: Ensure that the weekday for the cron job is valid if defined
      assert:
        that:
          - job.weekday is regex('^(\*|[0-6](-[0-6])?)(\/[1-9][0-9]*)?(,(\*|[0-6](-[0-6])?)(\/[1-9][0-9]*)?)*$')
      when: job.weekday is defined

  tags:
    - users
...
