# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects Users Ansible role.
#
# The Webarchitects Users Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Users Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Users Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
# The following will list the user state files that have changed
# however if the tasks were not fully completed then just using
# this would result in changes not being applied, so a check of
# the proposed vs the current state files is needed.
#
# - name: Users that need updating
#   ansible.builtin.set_fact:
#     users_check_state: "{{ users_check_state }} + [ '{{ result.user.key }}' ]"
#   when: result.changed
#   loop: "{{ users_state_file.results }}"
#   loop_control:
#     loop_var: result
#     label: "{{ result.user.key }}"

# The users_state_file is generated by a loop at the end of system.yml
- name: Users who have proposed state files changed
  ansible.builtin.debug:
    msg: "User with proposed state file changed: {{ result.user.key }}"
    verbosity: 1
  when: result.changed
  loop: "{{ users_state_file.results }}"
  loop_control:
    loop_var: result
    label: "{{ result.user.key }}"
  tags:
    - users

- name: Check users current state files
  ansible.builtin.include_tasks: user_state.yml
  loop: "{{ users | dict2items }}"
  loop_control:
    loop_var: user
    label: "{{ user.key }}"
  tags:
    - users

- name: Print the users to update
  ansible.builtin.debug:
    msg: "User to update: {{ users_update }}"
    verbosity: 2
...
