---
- name: "Check if a current state files exists for {{ user.key }}"
  stat:
    path: "{{ users_state_dir }}/current/{{ user.key }}.yml"
  register: users_current_state_file
  tags:
    - users

- name: "Current state file copied to the previous directory for {{ user.key }}"
  copy:
    src: "{{ users_state_dir }}/current/{{ user.key }}.yml"
    dest: "{{ users_state_dir }}/previous/{{ user.key }}.yml"
    remote_src: true
    mode: "0600"
    owner: root
    group: root
  when: ( users_current_state_file is defined ) and ( users_current_state_file.stat.exists )
  tags:
    - users

- name: "Proposed users state file copied to the current directory for {{ user.key }}"
  copy:
    src: "{{ users_state_dir }}/proposed/{{ user.key }}.yml"
    dest: "{{ users_state_dir }}/current/{{ user.key }}.yml"
    remote_src: true
    mode: "0600"
    owner: root
    group: root
  tags:
    - users
...
