---
- name: Directories for users state files present
  file:
    path: "{{ users_state_dir }}/{{ dir }}"
    state: directory
  loop:
    - current
    - previous
    - proposed
  loop_control:
    loop_var: dir

- name: Proposed users state files present
  template:
    src: user_state.yml.j2
    dest: "{{ users_state_dir }}/proposed/{{ user }}.yml"
  loop: "{{ users | dict2items }}" 
  loop_control:
    loop_var: user

- name: End test tasks
  fail:
    msg: "End of test"
...
