---
- name: Users groups
  block:

    - name: Add user to users_update array if they are in a group in the users_update_groups array
      ansible.builtin.set_fact:
        users_update: "{{ users_update | default([]) + [user.key] }}"
      when:
        - ( ( user.value.users_groups is defined ) and ( users_update_group in user.value.users_groups ) ) or ( users_update_group == user.key )
        - ( user.value.users_state is not defined ) or ( user.value.users_state != "ignore" )
        - ( user.key not in users_update )
      loop: "{{ users_update_groups }}"
      loop_control:
        loop_var: users_update_group

  tags:
    - users
...
