---
- name: "Apache VirtualHost checks {{ vhost.key }} for {{ user.key }}"
  block:

    # https://httpd.apache.org/docs/2.4/mod/mod_authn_core.html#authtype
    - name: "Check authtype is set to None, Basic, Digest or Form for users_apache_locations for {{ vhost.key }} VirtualHost for {{ user.key }} if defined"
      assert:
        that:
          - loc.authtype is regex("^(?i)None|Basic|Digest|Form$")
      when: loc.authtype is defined

    # https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html#require
    - name: "Check require for for locations for {{ vhost.key }} VirtualHost for {{ user.key }} if defined"
      block:

        - name: "Check that require is set to a non-empty array for users_apache_locations for {{ vhost.key }} VirtualHost for {{ user.key }} if defined"
          assert:
            that:
              - loc.require | length
              - loc.require[0] is defined

        - name: "Check that require is set to a valid option for users_apache_locations for {{ vhost.key }} VirtualHost for {{ user.key }} if defined"
          assert:
            that:
              - req is regex("(?i)[not]?all granted|[not]?all denied|[not]?env .*|[not]?method .*|[not]?expr .*|[not]?user .*|[not]?group .*|[not]?valid-user|[not]?ip .*")
          loop: "{{ loc.require }}"
          loop_control:
            loop_var: req
            label: "{{ req }}"

      when: loc.require is defined

    - name: "Check that redirect is set to a URL for users_apache_locations for {{ vhost.key }} VirtualHost for {{ user.key }} if defined"
      assert:
        that:
          - loc.redirect | length
          - loc.redirect is regex("http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+")
      when: loc.redirect is defined

  tags:
    - users
    - apache
...
