---
- name: "Check if {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_daily.sh exists"
  stat:
    path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_daily.sh"
  register: users_bin_cron_daily
  tags:
    - users

- name: "Blank {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_daily.sh in place"
  template:
    src: cron_daily.sh.j2
    dest: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_daily.sh"
    owner: "{{ user.key }}"
    group: "{{ user.value.users_group | default(user.key) }}"
    mode: "0750"
  when: not users_bin_cron_daily.stat.exists
  tags:
    - users

- name: "Daily scripts in place for {{ user.key }}"
  blockinfile:
    path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_daily.sh"
    block: |
      {% for users_daily_script in vhost.value.users_daily_scripts %}
      {{ users_daily_script }}
      {% endfor %}
    state: present
    create: false
    marker: "# {mark } ANSIBLE SCRIPTS"
    owner: "{{ user.key }}"
    group: "{{ user.value.users_group | default(user.key) }}"
    mode: "0700"
  tags:
    - users
...
