---
- name: "Check the DocumentRoot for each VirtualHost for {{ user.key }} contains valid characters"
  assert:
    that:
      - vhost.key is regex("^[a-zA-Z0-9/_-]*$")
    fail_msg: "Only letters, numbers, underscores, dashes and forward slashes can be present in the DocumentRoot path"

- name: "Check that each VirtualHost for {{ user.key }} has a ServerName"
  assert:
    that:
      - vhost.value.users_apache_server_name is defined
      - vhost.value.users_apache_server_name | length

# TODO: check this works with CNAMEs and RR DNS
- name: "Check that each VirtualHost for {{ user.key }} has a ServerName that resolves to a IPv4 address"
  include_tasks: user_check_domain.yml
  loop: "{{ vhost.value.users_apache_server_name }}"
  loop_control:
    loop_var: users_domain
...
