---
- name: "Set a fact for the {{ user.key }} users own group as a list"
  set_fact:
    users_own_group:
      - "{{ user.key }}"
  tags:
    - users

- name: "Set a fact for the {{ user.key }} users groups which includes the users own group, as a list"
  set_fact:
    users_all_groups:
      - "{{ user.value.users_groups | default(omit) + users_own_group }}"
  when: ( user.value.users_groups is defined ) and ( user.value.users_groups != [] )
  tags:
    - users

- name: "Print debugging info for {{ user.key }}"
  debug:
    msg:
      - "name: {{ user.key }}"
      - "group: {{ user.value.users_group | default(user.key) }}"
      - "groups: {{ user.value.users_groups | default([]) | join(',') or \ omit }}"
      - "all groups: {{ users_all_groups | default([]) | join(',') or \ omit }}"
      - "home: {{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
      - "shell: {{ user.value.users_shell | default('/bin/bash', true) }}"
      - "skeleton: {{ user.value.users_skel | default('') }}"
      - "system: {{ user.value.users_system | default('no', false) }}"
      - "editor: {{ user.value.users_editor | default('vim', true) }}"
      - "home owner: {{ user.value.users_home_owner | default(user.key) }}"
      - "home group: {{ user.value.users_home_group | default(user.key) }}"
      - "home mode: {{ user.value.users_home_mode | default('0700') }}"
      - "generate ssh key: {{ user.value.users_generate_ssh_key | default('false') }}"
      # - "email: {{ user.value.users_email }}"
    verbosity: 1

# TODO Check that the user doesn't already exist in getent_passwd
- name: "User account for {{ user.key }} present"
  user:
    name: "{{ user.key }}"
    group: "{{ user.value.users_group | default(user.key) }}"
    groups: "{{ users_all_groups | default([]) | join(',') or \ omit }}"
    home: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
    create_home: true
    shell: "{{ user.value.users_shell | default('/bin/bash', true) }}"
    skeleton: "{{ user.value.users_skel | default('') }}"
    generate_ssh_key: "{{ user.value.users_generate_ssh_key | default('false') }}"
    system: "{{ user.value.users_system | default('no', false) }}"
  tags:
    - users

- name: "Chown and chmod user home directory owner to {{ user.value.users_home_owner | default(user.key) }}:{{ user.value.users_home_group | default(user.value.users_group) | default(user.key) }} {{ user.value.users_home_mode | default('0750') }}"
  file:
    path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}"
    state: directory
    mode: "{{ user.value.users_home_mode | default('0750') }}"
    owner: "{{ user.value.users_home_owner | default(user.key) }}"
    group: "{{ user.value.users_home_group | default(user.value.users_group) | default(user.key) }}"
  tags:
    - users

- name: "Debug private directories present for {{ user.key }}"
  debug:
    msg:
      - "path: {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/{{ dir }}"
      - "state: directory"
      - "mode: {{ user.value.users_private_dirs_mode | default(users_private_dirs_mode) | default('0700') }}"
      - "owner: {{ user.key }}"
      - "group: {{ user.value.users_private_dirs_group | default(users_private_dirs_group) | default(user.value.users_group) | default(user.key) }}"
    verbosity: 2
  when:
    - ( user.value.users_system is not defined ) or ( user.value.users_system is defined and not user.value.users_system )
    - ( users_private_dirs is defined ) and ( users_private_dirs[0] is defined )
  loop: "{{ users_private_dirs }}"
  loop_control:
    loop_var: dir
    label: "{{ dir }}"
  tags:
    - users

- name: "Private directories present for {{ user.key }}"
  file:
    path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/{{ dir }}"
    state: directory
    mode: "{{ user.value.users_private_dirs_mode | default(users_private_dirs_mode) | default('0700') }}"
    owner: "{{ user.key }}"
    group: "{{ user.value.users_private_dirs_group | default(users_private_dirs_group) | default(user.value.users_group) | default(user.key) }}"
  when:
    - ( user.value.users_system is not defined ) or ( user.value.users_system is defined and not user.value.users_system )
    - ( users_private_dirs is defined ) and ( users_private_dirs[0] is defined )
  loop: "{{ users_private_dirs }}"
  loop_control:
    loop_var: dir
    label: "{{ dir }}"
  tags:
    - users

- name: "SSH public keys present for {{ user.key }}"
  include_tasks: ssh.yml
  when: ( user.value.users_ssh_public_keys is defined ) and ( user.value.users_ssh_public_keys != [] )
  tags:
    - users

- name: "Generate SSH ECDSA keypair for {{ user.key }}"
  command: ssh-keygen -q -t ed25519 -f "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.ssh/id_ed25519" -q -N "" -C "ansible-generated on {{ ansible_hostname }}"
  args:
    creates: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.ssh/id_ed25519"
  become: true
  become_user: "{{ user.key }}"
  when: ( user.value.users_generate_ssh_key is defined ) and ( user.value.users_generate_ssh_key )
  tags:
    - users

- name: "Set default editor for {{ user.key }}"
  copy:
    src: "files/{{ user.value.users_editor }}/selected_editor"
    dest: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.selected_editor"
    mode: "0644"
    owner: "{{ user.key }}"
    group: "{{ user.value.users_group | default(user.key) }}"
  when:
    - ( user.value.users_editor is defined ) and ( user.value.users_editor | length > 0 )
  tags:
    - users

- name: Nano and Vim tasks
  block:

    - name: "~/.vimrc present for {{ user.key }}"
      copy:
        src: "files/vim/vimrc"
        dest: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.vimrc"
        force: false
        mode: "0644"
        owner: "{{ user.key }}"
        group: "{{ user.value.users_group | default(user.key) }}"

    - name: "vim set to be default editor for {{ user.key }}"
      lineinfile:
        path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.bashrc"
        regexp: '^export EDITOR'
        line: 'export EDITOR="vim"'
        state: present
        create: true
        mode: "0644"
        owner: "{{ user.key }}"
        group: "{{ user.value.users_group | default(user.key) }}"
      when:
        - ( user.value.users_editor is defined ) and ( user.value.users_editor == "vim" )

    - name: "~/.nanorc present for {{ user.key }}"
      copy:
        src: "files/nano/nanorc"
        dest: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.nanorc"
        force: false
        mode: "0644"
        owner: "{{ user.key }}"
        group: "{{ user.value.users_group | default(user.key) }}"

    - name: "nano set to be default editor for {{ user.key }}"
      lineinfile:
        path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.bashrc"
        regexp: '^export EDITOR'
        line: 'export EDITOR="nano"'
        state: present
        create: true
        mode: "0644"
        owner: "{{ user.key }}"
        group: "{{ user.value.users_group | default(user.key) }}"
      when:
        - ( user.value.users_editor is defined ) and ( user.value.users_editor == "nano" )

  when:
    - ( user.value.users_system is not defined ) or ( user.value.users_system is defined and not user.value.users_system )
  tags:
    - users

- name: ".gitconfig in place for {{ user.key }}"
  template:
    src: gitconfig.j2
    dest: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/.gitconfig"
    mode: "0644"
    owner: "{{ user.key }}"
    group: "{{ user.value.users_group | default(user.key) }}"
    force: false
  when:
    - ( user.value.users_system is not defined ) or ( user.value.users_system is defined and not user.value.users_system )
    - ( user.value.users_name is defined ) and ( user.value.users_name | length > 0 )
    - ( user.value.users_email is defined ) and ( user.value.users_email | length > 0 )
  tags:
    - users

# TODO Generate README to document the account, MySQL, Apache etc.
...
