---
- name: "Check the DocumentRoot for the {{ vhost.key }} VirtualHost for {{ user.key }} contains valid characters"
  assert:
    that:
      - vhost.key is regex("^[a-zA-Z0-9/_-]*$")
    fail_msg: "Only letters, numbers, underscores, dashes and forward slashes can be present in the DocumentRoot path"

- name: "Check that the the {{ vhost.key }} VirtualHost for {{ user.key }} has a ServerName"
  assert:
    that:
      - vhost.value.users_apache_server_name is defined
      - vhost.value.users_apache_server_name | length

- name: "Check that the {{ vhost.key }} VirtualHost for {{ user.key }} has a ServerName that resolves to a IPv4 address"
  include_tasks: user_check_domain.yml
  vars:
    users_domain: "{{ vhost.value.users_apache_server_name }}"

- name: "Check ServerAlias' for {{ vhost.key }} VirtualHost for {{ user.key }}"
  block:

    - name: "Check that the ServerAlias' for {{ vhost.key }} VirtualHost for {{ user.key }} is a non-empty array"
      assert:
        that:
          - vhost.value.users_apache_server_aliases | length
          - vhost.value.users_apache_server_aliases[0] is defined

    - name: "Check that the {{ vhost.key }} VirtualHost for {{ user.key }} has ServerAlias' that resolve to IPv4 addresses"
      include_tasks: user_check_domain.yml
      vars:
        users_domain: "{{ domain }}"
      loop: "{{ vhost.value.users_apache_server.aliases }}"
      loop_control:
        loop_var: domain
        lable: "{{ domain }}"

  when: vhost.value.users_apache_server_aliases is defined
...
