---
- name: "Check if {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_hourly.sh exists"
  stat:
    path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_hourly.sh"
  register: users_bin_cron_hourly
  tags:
    - users

- name: "Blank {{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_hourly.sh in place"
  template:
    src: cron_hourly.sh.j2
    dest: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_hourly.sh"
    owner: "{{ user.key }}"
    group: "{{ user.value.users_group | default(user.key) }}"
    mode: "0750"
  when: not users_bin_cron_hourly.stat.exists
  tags:
    - users

- name: "Hourly scripts in place for {{ user.key }}"
  lineinfile:
    path: "{{ user.value.users_home | default(users_basedir + '/' + user.key) }}/bin/cron_hourly.sh"
    block: |
      {% for users_hourly_script in vhost.value.users_hourly_scripts %}
      {{ users_hourly_script }}
      {% endfor %}
    state: present
    create: false
    marker: "# {mark } ANSIBLE SCRIPTS"
    owner: "{{ user.key }}"
    group: "{{ user.value.users_group | default(user.key) }}"
    mode: "0750"
  tags:
    - users
...
